<h1>SETTING OPTIONS</h1>

In [ ]:
import pandas as pd
import numpy as np
pd.set_option('display.max_columns', 500) #SHOW UP TO 500 COLUMNS
pd.set_option('display.max_rows', 500) #SHOW UP TO 500 ROWS

In [ ]:
#df = pd.read_csv("https://raw.githubusercontent.com/mwaskom/seaborn-data/master/titanic.csv") 
df = pd.read_csv("https://raw.githubusercontent.com/pcm-dpc/COVID-19/master/dati-regioni/dpc-covid19-ita-regioni.csv")

#print(df)

# df.gr

In [ ]:
df.head()

,data,stato,codice_regione,denominazione_regione,lat,long,ricoverati_con_sintomi,terapia_intensiva,totale_ospedalizzati,isolamento_domiciliare,totale_positivi,variazione_totale_positivi,nuovi_positivi,dimessi_guariti,deceduti,casi_da_sospetto_diagnostico,casi_da_screening,totale_casi,tamponi,casi_testati,note
0,2020-02-24T18:00:00,ITA,13,Abruzzo,42.351222,13.398438,0,0,0,0,0,0,0,0,0,NaN,NaN,0,5,NaN,NaN
1,2020-02-24T18:00:00,ITA,17,Basilicata,40.639471,15.805148,0,0,0,0,0,0,0,0,0,NaN,NaN,0,0,NaN,NaN
2,2020-02-24T18:00:00,ITA,18,Calabria,38.905976,16.594402,0,0,0,0,0,0,0,0,0,NaN,NaN,0,1,NaN,NaN
3,2020-02-24T18:00:00,ITA,15,Campania,40.839566,14.250850,0,0,0,0,0,0,0,0,0,NaN,NaN,0,10,NaN,NaN
4,2020-02-24T18:00:00,ITA,8,Emilia-Romagna,44.494367,11.341721,10,2,12,6,18,0,18,0,0,NaN,NaN,18,148,NaN,NaN

In [ ]:
df.tail()

,data,stato,codice_regione,denominazione_regione,lat,long,ricoverati_con_sintomi,terapia_intensiva,totale_ospedalizzati,isolamento_domiciliare,totale_positivi,variazione_totale_positivi,nuovi_positivi,dimessi_guariti,deceduti,casi_da_sospetto_diagnostico,casi_da_screening,totale_casi,tamponi,casi_testati,note
5623,2020-11-17T17:00:00,ITA,19,Sicilia,38.115697,13.362357,1505,227,1732,29024,30756,991,1698,12964,971,27716.0,16975.0,44691,835534,577818.0,NaN
5624,2020-11-17T17:00:00,ITA,9,Toscana,43.769231,11.255889,1792,277,2069,52083,54152,301,2361,28078,1967,66908.0,17289.0,84197,1363146,870134.0,effettuati 48180 tamponi rapidi antigenici di...
5625,2020-11-17T17:00:00,ITA,10,Umbria,43.106758,12.388247,368,70,438,10806,11244,5,351,7991,275,5465.0,14045.0,19510,367077,206060.0,Si fa presente come nel computo dei ricoverati...
5626,2020-11-17T17:00:00,ITA,2,Valle d'Aosta,45.737503,7.320149,152,17,169,1994,2163,-103,154,3079,257,4884.0,615.0,5499,51410,30178.0,NaN
5627,2020-11-17T17:00:00,ITA,5,Veneto,45.434905,12.338452,1980,266,2246,60825,63071,373,3124,39928,2967,27936.0,78030.0,105966,2590427,1000577.0,Tamponi antigenici 623.625 Totale popolazione ...

In [ ]:
df.shape

(5628, 21)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5628 entries, 0 to 5627
Data columns (total 21 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   data                          5628 non-null   object
 1   stato                         5628 non-null   object
 2   codice_regione                5628 non-null   int64
 3   denominazione_regione         5628 non-null   object
 4   lat                           5628 non-null   float64
 5   long                          5628 non-null   float64
 6   ricoverati_con_sintomi        5628 non-null   int64
 7   terapia_intensiva             5628 non-null   int64
 8   totale_ospedalizzati          5628 non-null   int64
 9   isolamento_domiciliare        5628 non-null   int64
 10  totale_positivi               5628 non-null   int64
 11  variazione_totale_positivi    5628 non-null   int64
 12  nuovi_positivi                5628 non-null   int64
 13  dimessi_guariti               5628 non-null   int64
 14  deceduti                      5628 non-null   int64
 15  casi_da_sospetto_diagnostico  3066 non-null   float64
 16  casi_da_screening             3066 non-null   float64
 17  totale_casi                   5628 non-null   int64
 18  tamponi                       5628 non-null   int64
 19  casi_testati                  4473 non-null   float64
 20  note                          373 non-null    object
dtypes: float64(5), int64(12), object(4)
memory usage: 923.5+ KB

In [ ]:
df.dtypes

data                             object
stato                            object
codice_regione                    int64
denominazione_regione            object
lat                             float64
long                            float64
ricoverati_con_sintomi            int64
terapia_intensiva                 int64
totale_ospedalizzati              int64
isolamento_domiciliare            int64
totale_positivi                   int64
variazione_totale_positivi        int64
nuovi_positivi                    int64
dimessi_guariti                   int64
deceduti                          int64
casi_da_sospetto_diagnostico    float64
casi_da_screening               float64
totale_casi                       int64
tamponi                           int64
casi_testati                    float64
note                             object
dtype: object

### Summary of all numerical fields in the dataset

In [ ]:
df.describe(include = [np.number])

,codice_regione,lat,long,ricoverati_con_sintomi,terapia_intensiva,totale_ospedalizzati,isolamento_domiciliare,totale_positivi,variazione_totale_positivi,nuovi_positivi,dimessi_guariti,deceduti,casi_da_sospetto_diagnostico,casi_da_screening,totale_casi,tamponi,casi_testati
count,5628.000000,5628.000000,5628.000000,5628.000000,5628.000000,5628.000000,5628.000000,5628.000000,5628.000000,5628.000000,5628.000000,5628.000000,3066.000000,3066.000000,5628.000000,5.628000e+03,4.473000e+03
mean,11.857143,43.046293,12.225955,433.445984,47.334577,480.780561,3624.566809,4105.347370,130.346304,220.010128,7667.207711,1398.053838,13895.999674,4170.977169,13170.611940,3.044045e+05,2.293815e+05
std,6.274356,2.489002,2.659184,1188.620015,124.951570,1309.218949,10567.559528,11343.034395,584.338066,719.305739,15042.318316,3253.712843,25663.752913,9352.436662,26181.454942,4.648813e+05,2.826864e+05
min,1.000000,38.115697,7.320149,0.000000,0.000000,0.000000,0.000000,0.000000,-10202.000000,-229.000000,0.000000,0.000000,400.000000,0.000000,0.000000,0.000000e+00,3.482000e+03
25%,7.000000,41.125596,11.121231,14.000000,1.000000,15.000000,123.000000,147.750000,-3.000000,3.000000,560.500000,97.000000,1913.000000,110.250000,1342.250000,3.339500e+04,6.116400e+04
50%,12.000000,43.616760,12.388247,78.500000,7.000000,87.500000,653.000000,789.500000,6.000000,24.000000,2651.500000,349.000000,4606.500000,1132.500000,4317.000000,1.375305e+05,1.246830e+05
75%,17.000000,45.434905,13.768136,308.000000,37.000000,342.000000,2420.000000,2957.500000,69.000000,121.000000,7069.500000,994.000000,13609.500000,4161.750000,11084.500000,3.407052e+05,2.774210e+05
max,22.000000,46.499335,16.867367,12077.000000,1381.000000,13328.000000,153923.000000,162541.000000,10263.000000,11489.000000,157121.000000,19668.000000,251767.000000,81589.000000,333356.000000,3.606814e+06,2.177539e+06

### Summary of all categorical fields in the dataset

In [ ]:
df.describe(include = ['O'])

,data,stato,denominazione_regione,note
count,5628,5628,5628,373
unique,268,1,21,306
top,2020-08-12T17:00:00,ITA,Veneto,per 868 casi non e' disponibile la provenienza
freq,21,5628,268,5

**FREQUENCY BREAKDOWN**

In [ ]:
df['denominazione_regione'].value_counts()

Veneto                   268
P.A. Trento              268
Toscana                  268
Sicilia                  268
Umbria                   268
Abruzzo                  268
Molise                   268
Lombardia                268
Puglia                   268
Campania                 268
P.A. Bolzano             268
Sardegna                 268
Emilia-Romagna           268
Basilicata               268
Valle d'Aosta            268
Calabria                 268
Marche                   268
Lazio                    268
Piemonte                 268
Friuli Venezia Giulia    268
Liguria                  268
Name: denominazione_regione, dtype: int64

**PERCENTAGE BREAKDOWN**

In [ ]:
df['denominazione_regione'].value_counts(1)

Veneto                   0.047619
P.A. Trento              0.047619
Toscana                  0.047619
Sicilia                  0.047619
Umbria                   0.047619
Abruzzo                  0.047619
Molise                   0.047619
Lombardia                0.047619
Puglia                   0.047619
Campania                 0.047619
P.A. Bolzano             0.047619
Sardegna                 0.047619
Emilia-Romagna           0.047619
Basilicata               0.047619
Valle d'Aosta            0.047619
Calabria                 0.047619
Marche                   0.047619
Lazio                    0.047619
Piemonte                 0.047619
Friuli Venezia Giulia    0.047619
Liguria                  0.047619
Name: denominazione_regione, dtype: float64

**COUNT OF NULL VALUES**

In [ ]:
df['casi_testati'].isnull().sum()

1155

**COUNT OF NON-NULL VALUES**

In [ ]:
df['casi_testati'].notnull().sum()

4473

**LOOP THROUGH EACH COLUMN AND CHECK FOR NULLS**

In [ ]:
for i in range(len(df.columns)):
    print(df.columns[i] + ": " + str(df[df.columns[i]].isna().sum()))

data: 0
stato: 0
codice_regione: 0
denominazione_regione: 0
lat: 0
long: 0
ricoverati_con_sintomi: 0
terapia_intensiva: 0
totale_ospedalizzati: 0
isolamento_domiciliare: 0
totale_positivi: 0
variazione_totale_positivi: 0
nuovi_positivi: 0
dimessi_guariti: 0
deceduti: 0
casi_da_sospetto_diagnostico: 2562
casi_da_screening: 2562
totale_casi: 0
tamponi: 0
casi_testati: 1155
note: 5255

**GET THE UNIQUE VALUES IN THE COLUMN**

In [ ]:
df['casi_testati'].unique()

array([     nan,   22424.,    6528., ...,  206060.,   30178., 1000577.])

**SELECT ONE COLUMNS**

In [ ]:
df['casi_testati']

0             NaN
1             NaN
2             NaN
3             NaN
4             NaN
          ...
5623     577818.0
5624     870134.0
5625     206060.0
5626      30178.0
5627    1000577.0
Name: casi_testati, Length: 5628, dtype: float64

**SELECT MULTIPLE COLUMNS**

In [ ]:
df[['data', 'totale_casi', 'casi_testati']]

                     data  totale_casi  casi_testati
0     2020-02-24T18:00:00            0           NaN
1     2020-02-24T18:00:00            0           NaN
2     2020-02-24T18:00:00            0           NaN
3     2020-02-24T18:00:00            0           NaN
4     2020-02-24T18:00:00           18           NaN
...                   ...          ...           ...
5623  2020-11-17T17:00:00        44691      577818.0
5624  2020-11-17T17:00:00        84197      870134.0
5625  2020-11-17T17:00:00        19510      206060.0
5626  2020-11-17T17:00:00         5499       30178.0
5627  2020-11-17T17:00:00       105966     1000577.0

[5628 rows x 3 columns]

**SElECT COLUMN NAMES**

In [ ]:
df.columns

Index(['data', 'stato', 'codice_regione', 'denominazione_regione', 'lat',
       'long', 'ricoverati_con_sintomi', 'terapia_intensiva',
       'totale_ospedalizzati', 'isolamento_domiciliare', 'totale_positivi',
       'variazione_totale_positivi', 'nuovi_positivi', 'dimessi_guariti',
       'deceduti', 'casi_da_sospetto_diagnostico', 'casi_da_screening',
       'totale_casi', 'tamponi', 'casi_testati', 'note'],
      dtype='object')

**SELECT SUBSET OF DATA**

In [ ]:
df.loc[1500:1600,['casi_testati']]

      casi_testati
1500       44045.0
1501        7252.0
1502       20561.0
1503       25137.0
1504      126685.0
1505       67238.0
1506       25631.0
1507       82079.0
1508      118265.0
1509       27822.0
1510        6342.0
1511      227579.0
1512       31502.0
1513       15619.0
1514       39780.0
1515       49478.0
1516      138871.0
1517       50698.0
1518      125897.0
1519       37177.0
1520      262964.0
1521       45026.0
1522        7604.0
1523       20872.0
1524       26161.0
1525      131269.0
1526       68760.0
1527       26598.0
1528       83908.0
1529      121066.0
1530       28712.0
1531        6461.0
1532      231469.0
1533       32186.0
1534       15780.0
1535       40806.0
1536       50463.0
1537      141468.0
1538       51123.0
1539      130351.0
1540       38071.0
1541      262964.0
1542       46258.0
1543        7912.0
1544       21284.0
1545       28486.0
1546      134567.0
1547       51638.0
1548       27540.0
1549       85674.0
1550      124295.0
1551       29708.0
1552        6702.0
1553      236281.0
1554       32619.0
1555       16285.0
1556       41902.0
1557       51402.0
1558      144009.0
1559       52784.0
1560      133674.0
1561       39145.0
1562      277106.0
1563       47092.0
1564        8177.0
1565       21572.0
1566       29188.0
1567      138830.0
1568       53194.0
1569       28519.0
1570       88497.0
1571      126752.0
1572       30704.0
1573        6999.0
1574      240535.0
1575       33013.0
1576       16941.0
1577       42993.0
1578       52593.0
1579      146642.0
1580       55319.0
1581      137428.0
1582       39600.0
1583      282817.0
1584       47827.0
1585        8375.0
1586       21969.0
1587       30354.0
1588      141515.0
1589       54181.0
1590       29503.0
1591       90885.0
1592      129382.0
1593       31679.0
1594        7130.0
1595      244930.0
1596       33876.0
1597       17424.0
1598       44284.0
1599       53475.0
1600      149276.0

**SELECT ALL ROWS AND SPECIFIC COLUMN**

In [ ]:
df.loc[:,['casi_testati']]

      casi_testati
0              NaN
1              NaN
2              NaN
3              NaN
4              NaN
...            ...
5623      577818.0
5624      870134.0
5625      206060.0
5626       30178.0
5627     1000577.0

[5628 rows x 1 columns]

**SELECT COLUMN AT POSITION 2**

In [ ]:
df.iloc[:,2]

0       13
1       17
2       18
3       15
4        8
        ..
5623    19
5624     9
5625    10
5626     2
5627     5
Name: codice_regione, Length: 5628, dtype: int64

**SELECT ONE ROW AT POSITION 3**

In [ ]:
df.iloc[3,:]

data                            2020-02-24T18:00:00
stato                                           ITA
codice_regione                                   15
denominazione_regione                      Campania
lat                                         40.8396
long                                        14.2508
ricoverati_con_sintomi                            0
terapia_intensiva                                 0
totale_ospedalizzati                              0
isolamento_domiciliare                            0
totale_positivi                                   0
variazione_totale_positivi                        0
nuovi_positivi                                    0
dimessi_guariti                                   0
deceduti                                          0
casi_da_sospetto_diagnostico                    NaN
casi_da_screening                               NaN
totale_casi                                       0
tamponi                                          10
casi_testati                                    NaN
note                                            NaN
Name: 3, dtype: object

**MASK FOR STRING COLUMNS** - Select all rows with region as Lazio

In [ ]:
mask = df['denominazione_regione'] == "Lazio"
df[mask]

,data,stato,codice_regione,denominazione_regione,lat,long,ricoverati_con_sintomi,terapia_intensiva,totale_ospedalizzati,isolamento_domiciliare,totale_positivi,variazione_totale_positivi,nuovi_positivi,dimessi_guariti,deceduti,casi_da_sospetto_diagnostico,casi_da_screening,totale_casi,tamponi,casi_testati,note
6,2020-02-24T18:00:00,ITA,12,Lazio,41.89277,12.483667,1,1,2,0,2,0,2,1,0,NaN,NaN,3,124,NaN,NaN
27,2020-02-25T18:00:00,ITA,12,Lazio,41.89277,12.483667,1,1,2,0,2,0,0,1,0,NaN,NaN,3,124,NaN,NaN
48,2020-02-26T18:00:00,ITA,12,Lazio,41.89277,12.483667,0,0,0,0,0,-2,0,3,0,NaN,NaN,3,124,NaN,NaN
69,2020-02-27T18:00:00,ITA,12,Lazio,41.89277,12.483667,0,0,0,0,0,0,0,3,0,NaN,NaN,3,552,NaN,NaN
90,2020-02-28T18:00:00,ITA,12,Lazio,41.89277,12.483667,0,0,0,0,0,0,0,3,0,NaN,NaN,3,611,NaN,NaN
111,2020-02-29T17:00:00,ITA,12,Lazio,41.89277,12.483667,3,0,3,0,3,3,3,3,0,NaN,NaN,6,679,NaN,NaN
132,2020-03-01T17:00:00,ITA,12,Lazio,41.89277,12.483667,3,0,3,0,3,0,0,3,0,NaN,NaN,6,724,NaN,NaN
153,2020-03-02T18:00:00,ITA,12,Lazio,41.89277,12.483667,3,0,3,1,4,1,1,3,0,NaN,NaN,7,773,NaN,NaN
174,2020-03-03T18:00:00,ITA,12,Lazio,41.89277,12.483667,10,0,10,1,11,7,7,3,0,NaN,NaN,14,877,NaN,NaN
195,2020-03-04T17:00:00,ITA,12,Lazio,41.89277,12.483667,15,3,18,9,27,16,16,3,0,NaN,NaN,30,995,NaN,NaN
216,2020-03-05T17:00:00,ITA,12,Lazio,41.89277,12.483667,20,7,27,14,41,14,14,3,0,NaN,NaN,44,1175,NaN,NaN
237,2020-03-06T17:00:00,ITA,12,Lazio,41.89277,12.483667,26,8,34,16,50,9,10,3,1,NaN,NaN,54,1373,NaN,NaN
258,2020-03-07T18:00:00,ITA,12,Lazio,41.89277,12.483667,43,8,51,21,72,22,22,3,1,NaN,NaN,76,1582,NaN,NaN
279,2020-03-08T18:00:00,ITA,12,Lazio,41.89277,12.483667,47,8,55,26,81,9,11,3,3,NaN,NaN,87,1929,NaN,NaN
300,2020-03-09T18:00:00,ITA,12,Lazio,41.89277,12.483667,55,8,63,31,94,13,15,3,5,NaN,NaN,102,1929,NaN,NaN
321,2020-03-10T18:00:00,ITA,12,Lazio,41.89277,12.483667,50,15,65,34,99,5,14,11,6,NaN,NaN,116,3591,NaN,NaN
342,2020-03-11T17:00:00,ITA,12,Lazio,41.89277,12.483667,67,18,85,40,125,26,34,19,6,NaN,NaN,150,3591,NaN,NaN
363,2020-03-12T17:00:00,ITA,12,Lazio,41.89277,12.483667,85,20,105,67,172,47,50,19,9,NaN,NaN,200,5592,NaN,NaN
384,2020-03-13T17:00:00,ITA,12,Lazio,41.89277,12.483667,122,24,146,96,242,70,77,24,11,NaN,NaN,277,6491,NaN,NaN
405,2020-03-14T17:00:00,ITA,12,Lazio,41.89277,12.483667,181,25,206,114,320,78,80,24,13,NaN,NaN,357,7335,NaN,NaN
426,2020-03-15T17:00:00,ITA,12,Lazio,41.89277,12.483667,223,31,254,142,396,76,79,24,16,NaN,NaN,436,8345,NaN,NaN
447,2020-03-16T17:00:00,ITA,12,Lazio,41.89277,12.483667,267,31,298,174,472,76,87,32,19,NaN,NaN,523,9330,NaN,NaN
468,2020-03-17T17:00:00,ITA,12,Lazio,41.89277,12.483667,314,44,358,192,550,78,84,34,23,NaN,NaN,607,9436,NaN,NaN
489,2020-03-18T17:00:00,ITA,12,Lazio,41.89277,12.483667,374,44,418,232,650,100,117,42,32,NaN,NaN,724,11145,NaN,NaN
510,2020-03-19T17:00:00,ITA,12,Lazio,41.89277,12.483667,426,45,471,270,741,91,99,44,38,NaN,NaN,823,11145,NaN,NaN
531,2020-03-20T17:00:00,ITA,12,Lazio,41.89277,12.483667,537,47,584,328,912,171,185,53,43,NaN,NaN,1008,13889,NaN,NaN
552,2020-03-21T17:00:00,ITA,12,Lazio,41.89277,12.483667,591,70,661,425,1086,174,182,54,50,NaN,NaN,1190,13889,NaN,NaN
573,2020-03-22T17:00:00,ITA,12,Lazio,41.89277,12.483667,671,79,750,522,1272,186,193,58,53,NaN,NaN,1383,17845,NaN,NaN
594,2020-03-23T17:00:00,ITA,12,Lazio,41.89277,12.483667,718,96,814,600,1414,142,157,63,63,NaN,NaN,1540,18371,NaN,NaN
615,2020-03-24T17:00:00,ITA,12,Lazio,41.89277,12.483667,747,94,841,704,1545,131,188,103,80,NaN,NaN,1728,18371,NaN,NaN
636,2020-03-25T17:00:00,ITA,12,Lazio,41.89277,12.483667,805,101,906,769,1675,130,173,131,95,NaN,NaN,1901,20669,NaN,NaN
657,2020-03-26T17:00:00,ITA,12,Lazio,41.89277,12.483667,878,113,991,844,1835,160,195,155,106,NaN,NaN,2096,22771,NaN,NaN
678,2020-03-27T17:00:00,ITA,12,Lazio,41.89277,12.483667,992,126,1118,895,2013,178,199,164,118,NaN,NaN,2295,24106,NaN,NaN
699,2020-03-28T17:00:00,ITA,12,Lazio,41.89277,12.483667,985,133,1118,1063,2181,168,210,200,124,NaN,NaN,2505,27179,NaN,NaN
720,2020-03-29T17:00:00,ITA,12,Lazio,41.89277,12.483667,1062,133,1195,1167,2362,181,201,208,136,NaN,NaN,2706,27744,NaN,NaN
741,2020-03-30T17:00:00,ITA,12,Lazio,41.89277,12.483667,1079,154,1233,1264,2497,135,208,267,150,NaN,NaN,2914,32846,NaN,NaN
762,2020-03-31T17:00:00,ITA,12,Lazio,41.89277,12.483667,1127,173,1300,1342,2642,145,181,291,162,NaN,NaN,3095,34677,NaN,NaN
783,2020-04-01T17:00:00,ITA,12,Lazio,41.89277,12.483667,1131,177,1308,1450,2758,116,169,337,169,NaN,NaN,3264,35810,NaN,NaN
804,2020-04-02T17:00:00,ITA,12,Lazio,41.89277,12.483667,1169,181,1350,1529,2879,121,169,369,185,NaN,NaN,3433,41575,NaN,NaN
825,2020-04-03T17:00:00,ITA,12,Lazio,41.89277,12.483667,1194,188,1382,1627,3009,130,167,392,199,NaN,NaN,3600,43776,NaN,NaN
846,2020-04-04T17:00:00,ITA,12,Lazio,41.89277,12.483667,1236,193,1429,1677,3106,97,157,439,212,NaN,NaN,3757,44624,NaN,NaN
867,2020-04-05T17:00:00,ITA,12,Lazio,41.89277,12.483667,1235,197,1432,1754,3186,80,123,475,219,NaN,NaN,3880,44658,NaN,NaN
888,2020-04-06T17:00:00,ITA,12,Lazio,41.89277,12.483667,1235,197,1432,1868,3300,114,151,502,229,NaN,NaN,4031,47470,NaN,NaN
909,2020-04-07T17:00:00,ITA,12,Lazio,41.89277,12.483667,1229,192,1421,1944,3365,65,118,546,238,NaN,NaN,4149,48874,NaN,NaN
930,2020-04-08T17:00:00,ITA,12,Lazio,41.89277,12.483667,1241,196,1437,2011,3448,83,117,574,244,NaN,NaN,4266,55113,NaN,NaN
951,2020-04-09T17:00:00,ITA,12,Lazio,41.89277,12.483667,1244,198,1442,2090,3532,84,163,644,253,NaN,NaN,4429,58107,NaN,NaN
972,2020-04-10T17:00:00,ITA,12,Lazio,41.89277,12.483667,1236,201,1437,2196,3633,101,154,687,263,NaN,NaN,4583,61769,NaN,NaN
993,2020-04-11T17:00:00,ITA,12,Lazio,41.89277,12.483667,1264,203,1467,2263,3730,97,140,720,273,NaN,NaN,4723,65241,NaN,NaN
1014,2020-04-12T17:00:00,ITA,12,Lazio,41.89277,12.483667,1268,201,1469,2348,3817,87,122,749,279,NaN,NaN,4845,68954,NaN,NaN
1035,2020-04-13T17:00:00,ITA,12,Lazio,41.89277,12.483667,1314,200,1514,2406,3920,103,123,764,284,NaN,NaN,4968,72746,NaN,NaN
1056,2020-04-14T17:00:00,ITA,12,Lazio,41.89277,12.483667,1344,199,1543,2479,4022,102,143,789,300,NaN,NaN,5111,74650,NaN,NaN
1077,2020-04-15T17:00:00,ITA,12,Lazio,41.89277,12.483667,1342,196,1538,2509,4047,25,121,874,311,NaN,NaN,5232,75584,NaN,NaN
1098,2020-04-16T17:00:00,ITA,12,Lazio,41.89277,12.483667,1347,197,1544,2600,4144,97,148,920,316,NaN,NaN,5380,81993,NaN,NaN
1119,2020-04-17T17:00:00,ITA,12,Lazio,41.89277,12.483667,1332,187,1519,2695,4214,70,144,978,332,NaN,NaN,5524,84755,NaN,NaN
1140,2020-04-18T17:00:00,ITA,12,Lazio,41.89277,12.483667,1376,186,1562,2720,4282,68,144,1046,340,NaN,NaN,5668,89553,NaN,NaN
1161,2020-04-19T17:00:00,ITA,12,Lazio,41.89277,12.483667,1370,185,1555,2766,4321,39,87,1093,341,NaN,NaN,5755,91807,22702.0,NaN
1182,2020-04-20T17:00:00,ITA,12,Lazio,41.89277,12.483667,1388,185,1573,2792,4365,44,60,1101,349,NaN,NaN,5815,97823,23067.0,NaN
1203,2020-04-21T17:00:00,ITA,12,Lazio,41.89277,12.483667,1380,184,1564,2838,4402,37,80,1130,363,NaN,NaN,5895,100031,24046.0,NaN
1224,2020-04-22T17:00:00,ITA,12,Lazio,41.89277,12.483667,1384,187,1571,2892,4463,61,80,1142,370,NaN,NaN,5975,104062,25244.0,NaN
1245,2020-04-23T17:00:00,ITA,12,Lazio,41.89277,12.483667,1385,186,1571,2915,4486,23,79,1193,375,NaN,NaN,6054,111073,26298.0,pd-IT-0016
1266,2020-04-24T17:00:00,ITA,12,Lazio,41.89277,12.483667,1396,184,1580,2912,4492,6,78,1256,384,NaN,NaN,6132,114317,86545.0,NaN
1287,2020-04-25T17:00:00,ITA,12,Lazio,41.89277,12.483667,1421,183,1604,2957,4561,69,92,1276,387,NaN,NaN,6224,118354,90582.0,NaN
1308,2020-04-26T17:00:00,ITA,12,Lazio,41.89277,12.483667,1442,161,1603,2970,4573,12,85,1347,389,NaN,NaN,6309,121677,93811.0,NaN
1329,2020-04-27T17:00:00,ITA,12,Lazio,41.89277,12.483667,1464,143,1607,2955,4562,-11,83,1433,397,NaN,NaN,6392,124769,95719.0,NaN
1350,2020-04-28T17:00:00,ITA,12,Lazio,41.89277,12.483667,1468,132,1600,2962,4562,0,75,1491,414,NaN,NaN,6467,128664,98968.0,NaN
1371,2020-04-29T17:00:00,ITA,12,Lazio,41.89277,12.483667,1445,130,1575,2960,4535,-27,78,1579,431,NaN,NaN,6545,133503,103435.0,NaN
1392,2020-04-30T17:00:00,ITA,12,Lazio,41.89277,12.483667,1417,115,1532,2936,4468,-67,71,1707,441,NaN,NaN,6616,137596,107497.0,NaN
1413,2020-05-01T17:00:00,ITA,12,Lazio,41.89277,12.483667,1372,105,1477,2969,4446,-22,56,1744,482,NaN,NaN,6672,143804,111988.0,dc-IT-0014
1434,2020-05-02T17:00:00,ITA,12,Lazio,41.89277,12.483667,1370,96,1466,2986,4452,6,84,1807,497,NaN,NaN,6756,147078,114761.0,NaN
1455,2020-05-03T17:00:00,ITA,12,Lazio,41.89277,12.483667,1346,95,1441,2944,4385,-67,53,1916,508,NaN,NaN,6809,150912,117796.0,NaN
1476,2020-05-04T17:00:00,ITA,12,Lazio,41.89277,12.483667,1335,95,1430,2955,4385,0,38,1938,524,NaN,NaN,6847,153293,120095.0,NaN
1497,2020-05-05T17:00:00,ITA,12,Lazio,41.89277,12.483667,1315,91,1406,2964,4370,-15,67,2010,534,NaN,NaN,6914,157307,122541.0,NaN
1518,2020-05-06T17:00:00,ITA,12,Lazio,41.89277,12.483667,1351,91,1442,2991,4433,63,81,2024,538,NaN,NaN,6995,160894,125897.0,NaN
1539,2020-05-07T17:00:00,ITA,12,Lazio,41.89277,12.483667,1291,89,1380,2968,4348,-85,39,2143,543,NaN,NaN,7034,165340,130351.0,NaN
1560,2020-05-08T17:00:00,ITA,12,Lazio,41.89277,12.483667,1278,84,1362,2966,4328,-20,52,2209,549,NaN,NaN,7086,169499,133674.0,NaN
1581,2020-05-09T17:00:00,ITA,12,Lazio,41.89277,12.483667,1277,82,1359,2986,4345,17,47,2235,553,NaN,NaN,7133,174448,137428.0,NaN
1602,2020-05-10T17:00:00,ITA,12,Lazio,41.89277,12.483667,1265,84,1349,2937,4286,-59,32,2322,557,NaN,NaN,7165,178569,141233.0,NaN
1623,2020-05-11T17:00:00,ITA,12,Lazio,41.89277,12.483667,1266,83,1349,2945,4294,8,25,2334,562,NaN,NaN,7190,181398,143970.0,NaN
1644,2020-05-12T17:00:00,ITA,12,Lazio,41.89277,12.483667,1258,84,1342,2931,4273,-21,22,2373,566,NaN,NaN,7212,185085,147010.0,NaN
1665,2020-05-13T17:00:00,ITA,12,Lazio,41.89277,12.483667,1224,83,1307,2928,4235,-38,38,2438,577,NaN,NaN,7250,188632,150097.0,NaN
1686,2020-05-14T17:00:00,ITA,12,Lazio,41.89277,12.483667,1178,79,1257,2839,4096,-139,41,2600,595,NaN,NaN,7291,192917,153894.0,NaN
1707,2020-05-15T17:00:00,ITA,12,Lazio,41.89277,12.483667,1173,79,1252,2836,4088,-8,73,2672,604,NaN,NaN,7364,197599,157880.0,dc-IT-0030
1728,2020-05-16T17:00:00,ITA,12,Lazio,41.89277,12.483667,1156,76,1232,2790,4022,-66,32,2758,616,NaN,NaN,7396,201938,161405.0,NaN
1749,2020-05-17T17:00:00,ITA,12,Lazio,41.89277,12.483667,1150,74,1224,2686,3910,-112,50,2914,622,NaN,NaN,7446,206166,164779.0,NaN
1770,2020-05-18T17:00:00,ITA,12,Lazio,41.89277,12.483667,1137,73,1210,2616,3826,-84,39,3031,628,NaN,NaN,7485,209472,167859.0,NaN
1791,2020-05-19T17:00:00,ITA,12,Lazio,41.89277,12.483667,1124,74,1198,2588,3786,-40,20,3079,640,NaN,NaN,7505,213877,171353.0,NaN
1812,2020-05-20T17:00:00,ITA,12,Lazio,41.89277,12.483667,1119,74,1193,2593,3786,0,28,3100,647,NaN,NaN,7533,217849,173903.0,NaN
1833,2020-05-21T17:00:00,ITA,12,Lazio,41.89277,12.483667,1110,68,1178,2459,3637,-149,25,3259,662,NaN,NaN,7558,222071,177749.0,NaN
1854,2020-05-22T17:00:00,ITA,12,Lazio,41.89277,12.483667,1111,67,1178,2457,3635,-2,31,3285,669,NaN,NaN,7589,227090,182266.0,NaN
1875,2020-05-23T17:00:00,ITA,12,Lazio,41.89277,12.483667,1097,60,1157,2424,3581,-54,18,3350,676,NaN,NaN,7607,230743,185285.0,NaN
1896,2020-05-24T17:00:00,ITA,12,Lazio,41.89277,12.483667,1088,61,1149,2420,3569,-12,20,3374,684,NaN,NaN,7627,233498,187994.0,NaN
1917,2020-05-25T17:00:00,ITA,12,Lazio,41.89277,12.483667,1085,60,1145,2409,3554,-15,16,3401,688,NaN,NaN,7643,235840,190052.0,NaN
1938,2020-05-26T17:00:00,ITA,12,Lazio,41.89277,12.483667,1083,59,1142,2396,3538,-16,18,3430,693,NaN,NaN,7661,238967,192591.0,NaN
1959,2020-05-27T17:00:00,ITA,12,Lazio,41.89277,12.483667,1062,65,1127,2361,3488,-50,11,3483,701,NaN,NaN,7672,242287,195001.0,NaN
1980,2020-05-28T17:00:00,ITA,12,Lazio,41.89277,12.483667,1035,64,1099,2306,3405,-83,21,3580,708,NaN,NaN,7693,245993,198207.0,NaN
2001,2020-05-29T17:00:00,ITA,12,Lazio,41.89277,12.483667,817,59,876,2287,3163,-242,16,3825,721,NaN,NaN,7709,249267,201082.0,NaN
2022,2020-05-30T17:00:00,ITA,12,Lazio,41.89277,12.483667,769,58,827,2228,3055,-108,6,3932,728,NaN,NaN,7715,253388,204232.0,NaN
2043,2020-05-31T17:00:00,ITA,12,Lazio,41.89277,12.483667,730,57,787,2196,2983,-72,13,4010,735,NaN,NaN,7728,255474,206235.0,NaN
2064,2020-06-01T17:00:00,ITA,12,Lazio,41.89277,12.483667,594,56,650,2244,2894,-89,10,4105,739,NaN,NaN,7738,257563,208081.0,NaN
2085,2020-06-02T17:00:00,ITA,12,Lazio,41.89277,12.483667,580,56,636,2211,2847,-47,5,4155,741,NaN,NaN,7743,260102,209892.0,NaN
2106,2020-06-03T17:00:00,ITA,12,Lazio,41.89277,12.483667,519,51,570,2248,2818,-29,10,4188,747,NaN,NaN,7753,262461,211669.0,NaN
2127,2020-06-04T17:00:00,ITA,12,Lazio,41.89277,12.483667,488,51,539,2215,2754,-64,11,4260,750,NaN,NaN,7764,265380,214051.0,NaN
2148,2020-06-05T17:00:00,ITA,12,Lazio,41.89277,12.483667,480,51,531,2179,2710,-44,9,4309,754,NaN,NaN,7773,268561,216743.0,NaN
2169,2020-06-06T17:00:00,ITA,12,Lazio,41.89277,12.483667,477,49,526,2171,2697,-13,28,4346,758,NaN,NaN,7801,271662,219363.0,NaN
2190,2020-06-07T17:00:00,ITA,12,Lazio,41.89277,12.483667,467,49,516,2174,2690,-7,11,4362,760,NaN,NaN,7812,274129,221612.0,NaN
2211,2020-06-08T17:00:00,ITA,12,Lazio,41.89277,12.483667,466,49,515,2100,2615,-75,16,4450,763,NaN,NaN,7828,275885,222963.0,NaN
2232,2020-06-09T17:00:00,ITA,12,Lazio,41.89277,12.483667,462,47,509,2061,2570,-45,23,4515,766,NaN,NaN,7851,279572,225930.0,NaN
2253,2020-06-10T17:00:00,ITA,12,Lazio,41.89277,12.483667,368,47,415,2151,2566,-4,18,4533,770,NaN,NaN,7869,283630,229513.0,NaN
2274,2020-06-11T17:00:00,ITA,12,Lazio,41.89277,12.483667,320,46,366,2151,2517,-49,20,4596,776,NaN,NaN,7889,287888,233158.0,NaN
2295,2020-06-12T17:00:00,ITA,12,Lazio,41.89277,12.483667,293,47,340,1882,2222,-295,27,4913,781,NaN,NaN,7916,291869,237100.0,NaN
2316,2020-06-13T17:00:00,ITA,12,Lazio,41.89277,12.483667,303,45,348,1009,1357,-865,25,5778,806,NaN,NaN,7941,294654,239788.0,dc-IT-0048
2337,2020-06-14T17:00:00,ITA,12,Lazio,41.89277,12.483667,305,37,342,980,1322,-35,14,5825,808,NaN,NaN,7955,297615,242245.0,NaN
2358,2020-06-15T17:00:00,ITA,12,Lazio,41.89277,12.483667,304,37,341,951,1292,-30,3,5855,811,NaN,NaN,7958,299590,243805.0,NaN
2379,2020-06-16T17:00:00,ITA,12,Lazio,41.89277,12.483667,308,38,346,783,1129,-163,9,6024,814,NaN,NaN,7967,302305,245960.0,NaN
2400,2020-06-17T17:00:00,ITA,12,Lazio,41.89277,12.483667,284,38,322,717,1039,-90,10,6120,818,NaN,NaN,7977,305906,248746.0,NaN
2421,2020-06-18T17:00:00,ITA,12,Lazio,41.89277,12.483667,261,38,299,698,997,-42,9,6167,822,NaN,NaN,7986,309169,251673.0,NaN
2442,2020-06-19T17:00:00,ITA,12,Lazio,41.89277,12.483667,247,38,285,703,988,-9,9,6181,826,NaN,NaN,7995,312708,254525.0,NaN
2463,2020-06-20T17:00:00,ITA,12,Lazio,41.89277,12.483667,247,39,286,701,987,-1,14,6195,827,NaN,NaN,8009,316109,257265.0,NaN
2484,2020-06-21T17:00:00,ITA,12,Lazio,41.89277,12.483667,247,39,286,705,991,4,8,6199,827,NaN,NaN,8017,318264,259128.0,NaN
2505,2020-06-22T17:00:00,ITA,12,Lazio,41.89277,12.483667,201,23,224,721,945,-46,8,6250,830,NaN,NaN,8025,319581,260369.0,NaN
2526,2020-06-23T17:00:00,ITA,12,Lazio,41.89277,12.483667,184,16,200,686,886,-59,8,6315,832,NaN,NaN,8033,322341,263506.0,NaN
2547,2020-06-24T17:00:00,ITA,12,Lazio,41.89277,12.483667,181,13,194,675,869,-17,6,6337,833,NaN,NaN,8039,324492,265507.0,NaN
2568,2020-06-25T17:00:00,ITA,12,Lazio,41.89277,12.483667,181,12,193,669,862,-7,12,6354,835,5969.0,2082.0,8051,326651,267089.0,NaN
2589,2020-06-26T17:00:00,ITA,12,Lazio,41.89277,12.483667,185,13,198,618,816,-46,13,6412,836,5971.0,2093.0,8064,329074,269189.0,NaN
2610,2020-06-27T17:00:00,ITA,12,Lazio,41.89277,12.483667,185,13,198,629,827,11,18,6418,837,5977.0,2105.0,8082,331599,271209.0,NaN
2631,2020-06-28T17:00:00,ITA,12,Lazio,41.89277,12.483667,187,13,200,641,841,14,14,6418,837,5983.0,2113.0,8096,333852,272915.0,NaN
2652,2020-06-29T17:00:00,ITA,12,Lazio,41.89277,12.483667,190,13,203,637,840,-1,9,6428,837,5987.0,2118.0,8105,335751,274704.0,NaN
2673,2020-06-30T17:00:00,ITA,12,Lazio,41.89277,12.483667,189,13,202,634,836,-4,5,6437,837,5990.0,2120.0,8110,338035,276640.0,NaN
2694,2020-07-01T17:00:00,ITA,12,Lazio,41.89277,12.483667,190,12,202,630,832,-4,9,6448,839,5996.0,2123.0,8119,341083,279387.0,NaN
2715,2020-07-02T17:00:00,ITA,12,Lazio,41.89277,12.483667,188,11,199,632,831,-1,11,6460,839,6000.0,2130.0,8130,343882,281743.0,NaN
2736,2020-07-03T17:00:00,ITA,12,Lazio,41.89277,12.483667,188,11,199,627,826,-5,11,6475,840,6008.0,2133.0,8141,346239,283710.0,NaN
2757,2020-07-04T17:00:00,ITA,12,Lazio,41.89277,12.483667,197,11,208,646,854,28,31,6477,841,6019.0,2153.0,8172,348633,285697.0,NaN
2778,2020-07-05T17:00:00,ITA,12,Lazio,41.89277,12.483667,199,11,210,651,861,7,14,6484,841,6025.0,2161.0,8186,350978,287673.0,NaN
2799,2020-07-06T17:00:00,ITA,12,Lazio,41.89277,12.483667,200,12,212,658,870,9,19,6493,842,6035.0,2170.0,8205,353276,289493.0,NaN
2820,2020-07-07T17:00:00,ITA,12,Lazio,41.89277,12.483667,202,13,215,658,873,3,5,6495,842,6035.0,2175.0,8210,355305,291236.0,NaN
2841,2020-07-08T17:00:00,ITA,12,Lazio,41.89277,12.483667,198,13,211,663,874,1,14,6508,842,6043.0,2181.0,8224,357307,293031.0,NaN
2862,2020-07-09T17:00:00,ITA,12,Lazio,41.89277,12.483667,198,13,211,678,889,15,28,6520,843,6053.0,2199.0,8252,359842,295193.0,NaN
2883,2020-07-10T17:00:00,ITA,12,Lazio,41.89277,12.483667,197,13,210,691,901,12,23,6530,844,6063.0,2212.0,8275,362312,297217.0,NaN
2904,2020-07-11T17:00:00,ITA,12,Lazio,41.89277,12.483667,198,13,211,704,915,14,19,6535,844,6065.0,2229.0,8294,364876,299223.0,NaN
2925,2020-07-12T17:00:00,ITA,12,Lazio,41.89277,12.483667,197,12,209,704,913,-2,20,6557,844,6069.0,2245.0,8314,367461,301453.0,NaN
2946,2020-07-13T17:00:00,ITA,12,Lazio,41.89277,12.483667,191,11,202,690,892,-21,24,6601,845,6076.0,2262.0,8338,370462,304024.0,NaN
2967,2020-07-14T17:00:00,ITA,12,Lazio,41.89277,12.483667,188,10,198,696,894,2,18,6616,846,6086.0,2270.0,8356,373026,306387.0,NaN
2988,2020-07-15T17:00:00,ITA,12,Lazio,41.89277,12.483667,190,10,200,698,898,4,20,6631,847,6096.0,2280.0,8376,375364,308504.0,NaN
3009,2020-07-16T17:00:00,ITA,12,Lazio,41.89277,12.483667,175,9,184,666,850,-48,9,6687,848,6100.0,2285.0,8385,377936,310829.0,NaN
3030,2020-07-17T17:00:00,ITA,12,Lazio,41.89277,12.483667,175,9,184,668,852,2,14,6698,849,6105.0,2294.0,8399,381039,313544.0,NaN
3051,2020-07-18T17:00:00,ITA,12,Lazio,41.89277,12.483667,174,9,183,683,866,14,20,6703,850,6115.0,2304.0,8419,384054,316173.0,NaN
3072,2020-07-19T17:00:00,ITA,12,Lazio,41.89277,12.483667,180,9,189,683,872,6,17,6713,851,6121.0,2315.0,8436,387113,318945.0,NaN
3093,2020-07-20T17:00:00,ITA,12,Lazio,41.89277,12.483667,175,9,184,701,885,13,14,6714,851,6128.0,2322.0,8450,389441,321110.0,NaN
3114,2020-07-21T17:00:00,ITA,12,Lazio,41.89277,12.483667,175,9,184,697,881,-4,6,6722,853,6128.0,2328.0,8456,391123,322181.0,NaN
3135,2020-07-22T17:00:00,ITA,12,Lazio,41.89277,12.483667,174,9,183,706,889,8,16,6728,855,6131.0,2341.0,8472,394124,324963.0,NaN
3156,2020-07-23T17:00:00,ITA,12,Lazio,41.89277,12.483667,180,9,189,718,907,18,26,6735,856,6148.0,2350.0,8498,397055,327552.0,NaN
3177,2020-07-24T17:00:00,ITA,12,Lazio,41.89277,12.483667,184,9,193,723,916,9,18,6743,857,6155.0,2361.0,8516,399130,329353.0,NaN
3198,2020-07-25T17:00:00,ITA,12,Lazio,41.89277,12.483667,186,9,195,733,928,12,19,6749,858,6162.0,2373.0,8535,402012,331790.0,NaN
3219,2020-07-26T17:00:00,ITA,12,Lazio,41.89277,12.483667,189,9,198,737,935,7,19,6759,860,6163.0,2391.0,8554,404785,334242.0,NaN
3240,2020-07-27T17:00:00,ITA,12,Lazio,41.89277,12.483667,193,9,202,742,944,9,13,6762,861,6172.0,2395.0,8567,407440,336276.0,NaN
3261,2020-07-28T17:00:00,ITA,12,Lazio,41.89277,12.483667,194,9,203,739,942,-2,10,6773,862,6175.0,2402.0,8577,409189,337657.0,NaN
3282,2020-07-29T17:00:00,ITA,12,Lazio,41.89277,12.483667,198,9,207,762,969,27,34,6780,862,6187.0,2424.0,8611,412018,339954.0,NaN
3303,2020-07-30T17:00:00,ITA,12,Lazio,41.89277,12.483667,188,9,197,740,937,-32,18,6829,863,6193.0,2436.0,8629,414397,341764.0,NaN
3324,2020-07-31T17:00:00,ITA,12,Lazio,41.89277,12.483667,183,9,192,753,945,8,18,6839,863,6197.0,2450.0,8647,416921,343670.0,NaN

**MASK FOR NUMERIC COLUMN**

In [ ]:
mask2 = df['nuovi_positivi'] > 500
new_df = df[mask2]
new_df['denominazione_regione'].value_counts()

Lombardia                106
Piemonte                  65
Emilia-Romagna            52
Campania                  42
Veneto                    42
Toscana                   37
Lazio                     36
Sicilia                   31
Liguria                   28
Puglia                    25
Marche                    16
Umbria                    13
Friuli Venezia Giulia     12
P.A. Bolzano              12
Abruzzo                   11
Sardegna                   2
Calabria                   1
Name: denominazione_regione, dtype: int64

**MASK FOR ITMES IN LIST**

In [ ]:
# Get all the data for Lazio
mask3 = df['denominazione_regione'].isin(['Lazio'])
df[mask3]

,data,stato,codice_regione,denominazione_regione,lat,long,ricoverati_con_sintomi,terapia_intensiva,totale_ospedalizzati,isolamento_domiciliare,totale_positivi,variazione_totale_positivi,nuovi_positivi,dimessi_guariti,deceduti,casi_da_sospetto_diagnostico,casi_da_screening,totale_casi,tamponi,casi_testati,note
6,2020-02-24T18:00:00,ITA,12,Lazio,41.89277,12.483667,1,1,2,0,2,0,2,1,0,NaN,NaN,3,124,NaN,NaN
27,2020-02-25T18:00:00,ITA,12,Lazio,41.89277,12.483667,1,1,2,0,2,0,0,1,0,NaN,NaN,3,124,NaN,NaN
48,2020-02-26T18:00:00,ITA,12,Lazio,41.89277,12.483667,0,0,0,0,0,-2,0,3,0,NaN,NaN,3,124,NaN,NaN
69,2020-02-27T18:00:00,ITA,12,Lazio,41.89277,12.483667,0,0,0,0,0,0,0,3,0,NaN,NaN,3,552,NaN,NaN
90,2020-02-28T18:00:00,ITA,12,Lazio,41.89277,12.483667,0,0,0,0,0,0,0,3,0,NaN,NaN,3,611,NaN,NaN
111,2020-02-29T17:00:00,ITA,12,Lazio,41.89277,12.483667,3,0,3,0,3,3,3,3,0,NaN,NaN,6,679,NaN,NaN
132,2020-03-01T17:00:00,ITA,12,Lazio,41.89277,12.483667,3,0,3,0,3,0,0,3,0,NaN,NaN,6,724,NaN,NaN
153,2020-03-02T18:00:00,ITA,12,Lazio,41.89277,12.483667,3,0,3,1,4,1,1,3,0,NaN,NaN,7,773,NaN,NaN
174,2020-03-03T18:00:00,ITA,12,Lazio,41.89277,12.483667,10,0,10,1,11,7,7,3,0,NaN,NaN,14,877,NaN,NaN
195,2020-03-04T17:00:00,ITA,12,Lazio,41.89277,12.483667,15,3,18,9,27,16,16,3,0,NaN,NaN,30,995,NaN,NaN
216,2020-03-05T17:00:00,ITA,12,Lazio,41.89277,12.483667,20,7,27,14,41,14,14,3,0,NaN,NaN,44,1175,NaN,NaN
237,2020-03-06T17:00:00,ITA,12,Lazio,41.89277,12.483667,26,8,34,16,50,9,10,3,1,NaN,NaN,54,1373,NaN,NaN
258,2020-03-07T18:00:00,ITA,12,Lazio,41.89277,12.483667,43,8,51,21,72,22,22,3,1,NaN,NaN,76,1582,NaN,NaN
279,2020-03-08T18:00:00,ITA,12,Lazio,41.89277,12.483667,47,8,55,26,81,9,11,3,3,NaN,NaN,87,1929,NaN,NaN
300,2020-03-09T18:00:00,ITA,12,Lazio,41.89277,12.483667,55,8,63,31,94,13,15,3,5,NaN,NaN,102,1929,NaN,NaN
321,2020-03-10T18:00:00,ITA,12,Lazio,41.89277,12.483667,50,15,65,34,99,5,14,11,6,NaN,NaN,116,3591,NaN,NaN
342,2020-03-11T17:00:00,ITA,12,Lazio,41.89277,12.483667,67,18,85,40,125,26,34,19,6,NaN,NaN,150,3591,NaN,NaN
363,2020-03-12T17:00:00,ITA,12,Lazio,41.89277,12.483667,85,20,105,67,172,47,50,19,9,NaN,NaN,200,5592,NaN,NaN
384,2020-03-13T17:00:00,ITA,12,Lazio,41.89277,12.483667,122,24,146,96,242,70,77,24,11,NaN,NaN,277,6491,NaN,NaN
405,2020-03-14T17:00:00,ITA,12,Lazio,41.89277,12.483667,181,25,206,114,320,78,80,24,13,NaN,NaN,357,7335,NaN,NaN
426,2020-03-15T17:00:00,ITA,12,Lazio,41.89277,12.483667,223,31,254,142,396,76,79,24,16,NaN,NaN,436,8345,NaN,NaN
447,2020-03-16T17:00:00,ITA,12,Lazio,41.89277,12.483667,267,31,298,174,472,76,87,32,19,NaN,NaN,523,9330,NaN,NaN
468,2020-03-17T17:00:00,ITA,12,Lazio,41.89277,12.483667,314,44,358,192,550,78,84,34,23,NaN,NaN,607,9436,NaN,NaN
489,2020-03-18T17:00:00,ITA,12,Lazio,41.89277,12.483667,374,44,418,232,650,100,117,42,32,NaN,NaN,724,11145,NaN,NaN
510,2020-03-19T17:00:00,ITA,12,Lazio,41.89277,12.483667,426,45,471,270,741,91,99,44,38,NaN,NaN,823,11145,NaN,NaN
531,2020-03-20T17:00:00,ITA,12,Lazio,41.89277,12.483667,537,47,584,328,912,171,185,53,43,NaN,NaN,1008,13889,NaN,NaN
552,2020-03-21T17:00:00,ITA,12,Lazio,41.89277,12.483667,591,70,661,425,1086,174,182,54,50,NaN,NaN,1190,13889,NaN,NaN
573,2020-03-22T17:00:00,ITA,12,Lazio,41.89277,12.483667,671,79,750,522,1272,186,193,58,53,NaN,NaN,1383,17845,NaN,NaN
594,2020-03-23T17:00:00,ITA,12,Lazio,41.89277,12.483667,718,96,814,600,1414,142,157,63,63,NaN,NaN,1540,18371,NaN,NaN
615,2020-03-24T17:00:00,ITA,12,Lazio,41.89277,12.483667,747,94,841,704,1545,131,188,103,80,NaN,NaN,1728,18371,NaN,NaN
636,2020-03-25T17:00:00,ITA,12,Lazio,41.89277,12.483667,805,101,906,769,1675,130,173,131,95,NaN,NaN,1901,20669,NaN,NaN
657,2020-03-26T17:00:00,ITA,12,Lazio,41.89277,12.483667,878,113,991,844,1835,160,195,155,106,NaN,NaN,2096,22771,NaN,NaN
678,2020-03-27T17:00:00,ITA,12,Lazio,41.89277,12.483667,992,126,1118,895,2013,178,199,164,118,NaN,NaN,2295,24106,NaN,NaN
699,2020-03-28T17:00:00,ITA,12,Lazio,41.89277,12.483667,985,133,1118,1063,2181,168,210,200,124,NaN,NaN,2505,27179,NaN,NaN
720,2020-03-29T17:00:00,ITA,12,Lazio,41.89277,12.483667,1062,133,1195,1167,2362,181,201,208,136,NaN,NaN,2706,27744,NaN,NaN
741,2020-03-30T17:00:00,ITA,12,Lazio,41.89277,12.483667,1079,154,1233,1264,2497,135,208,267,150,NaN,NaN,2914,32846,NaN,NaN
762,2020-03-31T17:00:00,ITA,12,Lazio,41.89277,12.483667,1127,173,1300,1342,2642,145,181,291,162,NaN,NaN,3095,34677,NaN,NaN
783,2020-04-01T17:00:00,ITA,12,Lazio,41.89277,12.483667,1131,177,1308,1450,2758,116,169,337,169,NaN,NaN,3264,35810,NaN,NaN
804,2020-04-02T17:00:00,ITA,12,Lazio,41.89277,12.483667,1169,181,1350,1529,2879,121,169,369,185,NaN,NaN,3433,41575,NaN,NaN
825,2020-04-03T17:00:00,ITA,12,Lazio,41.89277,12.483667,1194,188,1382,1627,3009,130,167,392,199,NaN,NaN,3600,43776,NaN,NaN
846,2020-04-04T17:00:00,ITA,12,Lazio,41.89277,12.483667,1236,193,1429,1677,3106,97,157,439,212,NaN,NaN,3757,44624,NaN,NaN
867,2020-04-05T17:00:00,ITA,12,Lazio,41.89277,12.483667,1235,197,1432,1754,3186,80,123,475,219,NaN,NaN,3880,44658,NaN,NaN
888,2020-04-06T17:00:00,ITA,12,Lazio,41.89277,12.483667,1235,197,1432,1868,3300,114,151,502,229,NaN,NaN,4031,47470,NaN,NaN
909,2020-04-07T17:00:00,ITA,12,Lazio,41.89277,12.483667,1229,192,1421,1944,3365,65,118,546,238,NaN,NaN,4149,48874,NaN,NaN
930,2020-04-08T17:00:00,ITA,12,Lazio,41.89277,12.483667,1241,196,1437,2011,3448,83,117,574,244,NaN,NaN,4266,55113,NaN,NaN
951,2020-04-09T17:00:00,ITA,12,Lazio,41.89277,12.483667,1244,198,1442,2090,3532,84,163,644,253,NaN,NaN,4429,58107,NaN,NaN
972,2020-04-10T17:00:00,ITA,12,Lazio,41.89277,12.483667,1236,201,1437,2196,3633,101,154,687,263,NaN,NaN,4583,61769,NaN,NaN
993,2020-04-11T17:00:00,ITA,12,Lazio,41.89277,12.483667,1264,203,1467,2263,3730,97,140,720,273,NaN,NaN,4723,65241,NaN,NaN
1014,2020-04-12T17:00:00,ITA,12,Lazio,41.89277,12.483667,1268,201,1469,2348,3817,87,122,749,279,NaN,NaN,4845,68954,NaN,NaN
1035,2020-04-13T17:00:00,ITA,12,Lazio,41.89277,12.483667,1314,200,1514,2406,3920,103,123,764,284,NaN,NaN,4968,72746,NaN,NaN
1056,2020-04-14T17:00:00,ITA,12,Lazio,41.89277,12.483667,1344,199,1543,2479,4022,102,143,789,300,NaN,NaN,5111,74650,NaN,NaN
1077,2020-04-15T17:00:00,ITA,12,Lazio,41.89277,12.483667,1342,196,1538,2509,4047,25,121,874,311,NaN,NaN,5232,75584,NaN,NaN
1098,2020-04-16T17:00:00,ITA,12,Lazio,41.89277,12.483667,1347,197,1544,2600,4144,97,148,920,316,NaN,NaN,5380,81993,NaN,NaN
1119,2020-04-17T17:00:00,ITA,12,Lazio,41.89277,12.483667,1332,187,1519,2695,4214,70,144,978,332,NaN,NaN,5524,84755,NaN,NaN
1140,2020-04-18T17:00:00,ITA,12,Lazio,41.89277,12.483667,1376,186,1562,2720,4282,68,144,1046,340,NaN,NaN,5668,89553,NaN,NaN
1161,2020-04-19T17:00:00,ITA,12,Lazio,41.89277,12.483667,1370,185,1555,2766,4321,39,87,1093,341,NaN,NaN,5755,91807,22702.0,NaN
1182,2020-04-20T17:00:00,ITA,12,Lazio,41.89277,12.483667,1388,185,1573,2792,4365,44,60,1101,349,NaN,NaN,5815,97823,23067.0,NaN
1203,2020-04-21T17:00:00,ITA,12,Lazio,41.89277,12.483667,1380,184,1564,2838,4402,37,80,1130,363,NaN,NaN,5895,100031,24046.0,NaN
1224,2020-04-22T17:00:00,ITA,12,Lazio,41.89277,12.483667,1384,187,1571,2892,4463,61,80,1142,370,NaN,NaN,5975,104062,25244.0,NaN
1245,2020-04-23T17:00:00,ITA,12,Lazio,41.89277,12.483667,1385,186,1571,2915,4486,23,79,1193,375,NaN,NaN,6054,111073,26298.0,pd-IT-0016
1266,2020-04-24T17:00:00,ITA,12,Lazio,41.89277,12.483667,1396,184,1580,2912,4492,6,78,1256,384,NaN,NaN,6132,114317,86545.0,NaN
1287,2020-04-25T17:00:00,ITA,12,Lazio,41.89277,12.483667,1421,183,1604,2957,4561,69,92,1276,387,NaN,NaN,6224,118354,90582.0,NaN
1308,2020-04-26T17:00:00,ITA,12,Lazio,41.89277,12.483667,1442,161,1603,2970,4573,12,85,1347,389,NaN,NaN,6309,121677,93811.0,NaN
1329,2020-04-27T17:00:00,ITA,12,Lazio,41.89277,12.483667,1464,143,1607,2955,4562,-11,83,1433,397,NaN,NaN,6392,124769,95719.0,NaN
1350,2020-04-28T17:00:00,ITA,12,Lazio,41.89277,12.483667,1468,132,1600,2962,4562,0,75,1491,414,NaN,NaN,6467,128664,98968.0,NaN
1371,2020-04-29T17:00:00,ITA,12,Lazio,41.89277,12.483667,1445,130,1575,2960,4535,-27,78,1579,431,NaN,NaN,6545,133503,103435.0,NaN
1392,2020-04-30T17:00:00,ITA,12,Lazio,41.89277,12.483667,1417,115,1532,2936,4468,-67,71,1707,441,NaN,NaN,6616,137596,107497.0,NaN
1413,2020-05-01T17:00:00,ITA,12,Lazio,41.89277,12.483667,1372,105,1477,2969,4446,-22,56,1744,482,NaN,NaN,6672,143804,111988.0,dc-IT-0014
1434,2020-05-02T17:00:00,ITA,12,Lazio,41.89277,12.483667,1370,96,1466,2986,4452,6,84,1807,497,NaN,NaN,6756,147078,114761.0,NaN
1455,2020-05-03T17:00:00,ITA,12,Lazio,41.89277,12.483667,1346,95,1441,2944,4385,-67,53,1916,508,NaN,NaN,6809,150912,117796.0,NaN
1476,2020-05-04T17:00:00,ITA,12,Lazio,41.89277,12.483667,1335,95,1430,2955,4385,0,38,1938,524,NaN,NaN,6847,153293,120095.0,NaN
1497,2020-05-05T17:00:00,ITA,12,Lazio,41.89277,12.483667,1315,91,1406,2964,4370,-15,67,2010,534,NaN,NaN,6914,157307,122541.0,NaN
1518,2020-05-06T17:00:00,ITA,12,Lazio,41.89277,12.483667,1351,91,1442,2991,4433,63,81,2024,538,NaN,NaN,6995,160894,125897.0,NaN
1539,2020-05-07T17:00:00,ITA,12,Lazio,41.89277,12.483667,1291,89,1380,2968,4348,-85,39,2143,543,NaN,NaN,7034,165340,130351.0,NaN
1560,2020-05-08T17:00:00,ITA,12,Lazio,41.89277,12.483667,1278,84,1362,2966,4328,-20,52,2209,549,NaN,NaN,7086,169499,133674.0,NaN
1581,2020-05-09T17:00:00,ITA,12,Lazio,41.89277,12.483667,1277,82,1359,2986,4345,17,47,2235,553,NaN,NaN,7133,174448,137428.0,NaN
1602,2020-05-10T17:00:00,ITA,12,Lazio,41.89277,12.483667,1265,84,1349,2937,4286,-59,32,2322,557,NaN,NaN,7165,178569,141233.0,NaN
1623,2020-05-11T17:00:00,ITA,12,Lazio,41.89277,12.483667,1266,83,1349,2945,4294,8,25,2334,562,NaN,NaN,7190,181398,143970.0,NaN
1644,2020-05-12T17:00:00,ITA,12,Lazio,41.89277,12.483667,1258,84,1342,2931,4273,-21,22,2373,566,NaN,NaN,7212,185085,147010.0,NaN
1665,2020-05-13T17:00:00,ITA,12,Lazio,41.89277,12.483667,1224,83,1307,2928,4235,-38,38,2438,577,NaN,NaN,7250,188632,150097.0,NaN
1686,2020-05-14T17:00:00,ITA,12,Lazio,41.89277,12.483667,1178,79,1257,2839,4096,-139,41,2600,595,NaN,NaN,7291,192917,153894.0,NaN
1707,2020-05-15T17:00:00,ITA,12,Lazio,41.89277,12.483667,1173,79,1252,2836,4088,-8,73,2672,604,NaN,NaN,7364,197599,157880.0,dc-IT-0030
1728,2020-05-16T17:00:00,ITA,12,Lazio,41.89277,12.483667,1156,76,1232,2790,4022,-66,32,2758,616,NaN,NaN,7396,201938,161405.0,NaN
1749,2020-05-17T17:00:00,ITA,12,Lazio,41.89277,12.483667,1150,74,1224,2686,3910,-112,50,2914,622,NaN,NaN,7446,206166,164779.0,NaN
1770,2020-05-18T17:00:00,ITA,12,Lazio,41.89277,12.483667,1137,73,1210,2616,3826,-84,39,3031,628,NaN,NaN,7485,209472,167859.0,NaN
1791,2020-05-19T17:00:00,ITA,12,Lazio,41.89277,12.483667,1124,74,1198,2588,3786,-40,20,3079,640,NaN,NaN,7505,213877,171353.0,NaN
1812,2020-05-20T17:00:00,ITA,12,Lazio,41.89277,12.483667,1119,74,1193,2593,3786,0,28,3100,647,NaN,NaN,7533,217849,173903.0,NaN
1833,2020-05-21T17:00:00,ITA,12,Lazio,41.89277,12.483667,1110,68,1178,2459,3637,-149,25,3259,662,NaN,NaN,7558,222071,177749.0,NaN
1854,2020-05-22T17:00:00,ITA,12,Lazio,41.89277,12.483667,1111,67,1178,2457,3635,-2,31,3285,669,NaN,NaN,7589,227090,182266.0,NaN
1875,2020-05-23T17:00:00,ITA,12,Lazio,41.89277,12.483667,1097,60,1157,2424,3581,-54,18,3350,676,NaN,NaN,7607,230743,185285.0,NaN
1896,2020-05-24T17:00:00,ITA,12,Lazio,41.89277,12.483667,1088,61,1149,2420,3569,-12,20,3374,684,NaN,NaN,7627,233498,187994.0,NaN
1917,2020-05-25T17:00:00,ITA,12,Lazio,41.89277,12.483667,1085,60,1145,2409,3554,-15,16,3401,688,NaN,NaN,7643,235840,190052.0,NaN
1938,2020-05-26T17:00:00,ITA,12,Lazio,41.89277,12.483667,1083,59,1142,2396,3538,-16,18,3430,693,NaN,NaN,7661,238967,192591.0,NaN
1959,2020-05-27T17:00:00,ITA,12,Lazio,41.89277,12.483667,1062,65,1127,2361,3488,-50,11,3483,701,NaN,NaN,7672,242287,195001.0,NaN
1980,2020-05-28T17:00:00,ITA,12,Lazio,41.89277,12.483667,1035,64,1099,2306,3405,-83,21,3580,708,NaN,NaN,7693,245993,198207.0,NaN
2001,2020-05-29T17:00:00,ITA,12,Lazio,41.89277,12.483667,817,59,876,2287,3163,-242,16,3825,721,NaN,NaN,7709,249267,201082.0,NaN
2022,2020-05-30T17:00:00,ITA,12,Lazio,41.89277,12.483667,769,58,827,2228,3055,-108,6,3932,728,NaN,NaN,7715,253388,204232.0,NaN
2043,2020-05-31T17:00:00,ITA,12,Lazio,41.89277,12.483667,730,57,787,2196,2983,-72,13,4010,735,NaN,NaN,7728,255474,206235.0,NaN
2064,2020-06-01T17:00:00,ITA,12,Lazio,41.89277,12.483667,594,56,650,2244,2894,-89,10,4105,739,NaN,NaN,7738,257563,208081.0,NaN
2085,2020-06-02T17:00:00,ITA,12,Lazio,41.89277,12.483667,580,56,636,2211,2847,-47,5,4155,741,NaN,NaN,7743,260102,209892.0,NaN
2106,2020-06-03T17:00:00,ITA,12,Lazio,41.89277,12.483667,519,51,570,2248,2818,-29,10,4188,747,NaN,NaN,7753,262461,211669.0,NaN
2127,2020-06-04T17:00:00,ITA,12,Lazio,41.89277,12.483667,488,51,539,2215,2754,-64,11,4260,750,NaN,NaN,7764,265380,214051.0,NaN
2148,2020-06-05T17:00:00,ITA,12,Lazio,41.89277,12.483667,480,51,531,2179,2710,-44,9,4309,754,NaN,NaN,7773,268561,216743.0,NaN
2169,2020-06-06T17:00:00,ITA,12,Lazio,41.89277,12.483667,477,49,526,2171,2697,-13,28,4346,758,NaN,NaN,7801,271662,219363.0,NaN
2190,2020-06-07T17:00:00,ITA,12,Lazio,41.89277,12.483667,467,49,516,2174,2690,-7,11,4362,760,NaN,NaN,7812,274129,221612.0,NaN
2211,2020-06-08T17:00:00,ITA,12,Lazio,41.89277,12.483667,466,49,515,2100,2615,-75,16,4450,763,NaN,NaN,7828,275885,222963.0,NaN
2232,2020-06-09T17:00:00,ITA,12,Lazio,41.89277,12.483667,462,47,509,2061,2570,-45,23,4515,766,NaN,NaN,7851,279572,225930.0,NaN
2253,2020-06-10T17:00:00,ITA,12,Lazio,41.89277,12.483667,368,47,415,2151,2566,-4,18,4533,770,NaN,NaN,7869,283630,229513.0,NaN
2274,2020-06-11T17:00:00,ITA,12,Lazio,41.89277,12.483667,320,46,366,2151,2517,-49,20,4596,776,NaN,NaN,7889,287888,233158.0,NaN
2295,2020-06-12T17:00:00,ITA,12,Lazio,41.89277,12.483667,293,47,340,1882,2222,-295,27,4913,781,NaN,NaN,7916,291869,237100.0,NaN
2316,2020-06-13T17:00:00,ITA,12,Lazio,41.89277,12.483667,303,45,348,1009,1357,-865,25,5778,806,NaN,NaN,7941,294654,239788.0,dc-IT-0048
2337,2020-06-14T17:00:00,ITA,12,Lazio,41.89277,12.483667,305,37,342,980,1322,-35,14,5825,808,NaN,NaN,7955,297615,242245.0,NaN
2358,2020-06-15T17:00:00,ITA,12,Lazio,41.89277,12.483667,304,37,341,951,1292,-30,3,5855,811,NaN,NaN,7958,299590,243805.0,NaN
2379,2020-06-16T17:00:00,ITA,12,Lazio,41.89277,12.483667,308,38,346,783,1129,-163,9,6024,814,NaN,NaN,7967,302305,245960.0,NaN
2400,2020-06-17T17:00:00,ITA,12,Lazio,41.89277,12.483667,284,38,322,717,1039,-90,10,6120,818,NaN,NaN,7977,305906,248746.0,NaN
2421,2020-06-18T17:00:00,ITA,12,Lazio,41.89277,12.483667,261,38,299,698,997,-42,9,6167,822,NaN,NaN,7986,309169,251673.0,NaN
2442,2020-06-19T17:00:00,ITA,12,Lazio,41.89277,12.483667,247,38,285,703,988,-9,9,6181,826,NaN,NaN,7995,312708,254525.0,NaN
2463,2020-06-20T17:00:00,ITA,12,Lazio,41.89277,12.483667,247,39,286,701,987,-1,14,6195,827,NaN,NaN,8009,316109,257265.0,NaN
2484,2020-06-21T17:00:00,ITA,12,Lazio,41.89277,12.483667,247,39,286,705,991,4,8,6199,827,NaN,NaN,8017,318264,259128.0,NaN
2505,2020-06-22T17:00:00,ITA,12,Lazio,41.89277,12.483667,201,23,224,721,945,-46,8,6250,830,NaN,NaN,8025,319581,260369.0,NaN
2526,2020-06-23T17:00:00,ITA,12,Lazio,41.89277,12.483667,184,16,200,686,886,-59,8,6315,832,NaN,NaN,8033,322341,263506.0,NaN
2547,2020-06-24T17:00:00,ITA,12,Lazio,41.89277,12.483667,181,13,194,675,869,-17,6,6337,833,NaN,NaN,8039,324492,265507.0,NaN
2568,2020-06-25T17:00:00,ITA,12,Lazio,41.89277,12.483667,181,12,193,669,862,-7,12,6354,835,5969.0,2082.0,8051,326651,267089.0,NaN
2589,2020-06-26T17:00:00,ITA,12,Lazio,41.89277,12.483667,185,13,198,618,816,-46,13,6412,836,5971.0,2093.0,8064,329074,269189.0,NaN
2610,2020-06-27T17:00:00,ITA,12,Lazio,41.89277,12.483667,185,13,198,629,827,11,18,6418,837,5977.0,2105.0,8082,331599,271209.0,NaN
2631,2020-06-28T17:00:00,ITA,12,Lazio,41.89277,12.483667,187,13,200,641,841,14,14,6418,837,5983.0,2113.0,8096,333852,272915.0,NaN
2652,2020-06-29T17:00:00,ITA,12,Lazio,41.89277,12.483667,190,13,203,637,840,-1,9,6428,837,5987.0,2118.0,8105,335751,274704.0,NaN
2673,2020-06-30T17:00:00,ITA,12,Lazio,41.89277,12.483667,189,13,202,634,836,-4,5,6437,837,5990.0,2120.0,8110,338035,276640.0,NaN
2694,2020-07-01T17:00:00,ITA,12,Lazio,41.89277,12.483667,190,12,202,630,832,-4,9,6448,839,5996.0,2123.0,8119,341083,279387.0,NaN
2715,2020-07-02T17:00:00,ITA,12,Lazio,41.89277,12.483667,188,11,199,632,831,-1,11,6460,839,6000.0,2130.0,8130,343882,281743.0,NaN
2736,2020-07-03T17:00:00,ITA,12,Lazio,41.89277,12.483667,188,11,199,627,826,-5,11,6475,840,6008.0,2133.0,8141,346239,283710.0,NaN
2757,2020-07-04T17:00:00,ITA,12,Lazio,41.89277,12.483667,197,11,208,646,854,28,31,6477,841,6019.0,2153.0,8172,348633,285697.0,NaN
2778,2020-07-05T17:00:00,ITA,12,Lazio,41.89277,12.483667,199,11,210,651,861,7,14,6484,841,6025.0,2161.0,8186,350978,287673.0,NaN
2799,2020-07-06T17:00:00,ITA,12,Lazio,41.89277,12.483667,200,12,212,658,870,9,19,6493,842,6035.0,2170.0,8205,353276,289493.0,NaN
2820,2020-07-07T17:00:00,ITA,12,Lazio,41.89277,12.483667,202,13,215,658,873,3,5,6495,842,6035.0,2175.0,8210,355305,291236.0,NaN
2841,2020-07-08T17:00:00,ITA,12,Lazio,41.89277,12.483667,198,13,211,663,874,1,14,6508,842,6043.0,2181.0,8224,357307,293031.0,NaN
2862,2020-07-09T17:00:00,ITA,12,Lazio,41.89277,12.483667,198,13,211,678,889,15,28,6520,843,6053.0,2199.0,8252,359842,295193.0,NaN
2883,2020-07-10T17:00:00,ITA,12,Lazio,41.89277,12.483667,197,13,210,691,901,12,23,6530,844,6063.0,2212.0,8275,362312,297217.0,NaN
2904,2020-07-11T17:00:00,ITA,12,Lazio,41.89277,12.483667,198,13,211,704,915,14,19,6535,844,6065.0,2229.0,8294,364876,299223.0,NaN
2925,2020-07-12T17:00:00,ITA,12,Lazio,41.89277,12.483667,197,12,209,704,913,-2,20,6557,844,6069.0,2245.0,8314,367461,301453.0,NaN
2946,2020-07-13T17:00:00,ITA,12,Lazio,41.89277,12.483667,191,11,202,690,892,-21,24,6601,845,6076.0,2262.0,8338,370462,304024.0,NaN
2967,2020-07-14T17:00:00,ITA,12,Lazio,41.89277,12.483667,188,10,198,696,894,2,18,6616,846,6086.0,2270.0,8356,373026,306387.0,NaN
2988,2020-07-15T17:00:00,ITA,12,Lazio,41.89277,12.483667,190,10,200,698,898,4,20,6631,847,6096.0,2280.0,8376,375364,308504.0,NaN
3009,2020-07-16T17:00:00,ITA,12,Lazio,41.89277,12.483667,175,9,184,666,850,-48,9,6687,848,6100.0,2285.0,8385,377936,310829.0,NaN
3030,2020-07-17T17:00:00,ITA,12,Lazio,41.89277,12.483667,175,9,184,668,852,2,14,6698,849,6105.0,2294.0,8399,381039,313544.0,NaN
3051,2020-07-18T17:00:00,ITA,12,Lazio,41.89277,12.483667,174,9,183,683,866,14,20,6703,850,6115.0,2304.0,8419,384054,316173.0,NaN
3072,2020-07-19T17:00:00,ITA,12,Lazio,41.89277,12.483667,180,9,189,683,872,6,17,6713,851,6121.0,2315.0,8436,387113,318945.0,NaN
3093,2020-07-20T17:00:00,ITA,12,Lazio,41.89277,12.483667,175,9,184,701,885,13,14,6714,851,6128.0,2322.0,8450,389441,321110.0,NaN
3114,2020-07-21T17:00:00,ITA,12,Lazio,41.89277,12.483667,175,9,184,697,881,-4,6,6722,853,6128.0,2328.0,8456,391123,322181.0,NaN
3135,2020-07-22T17:00:00,ITA,12,Lazio,41.89277,12.483667,174,9,183,706,889,8,16,6728,855,6131.0,2341.0,8472,394124,324963.0,NaN
3156,2020-07-23T17:00:00,ITA,12,Lazio,41.89277,12.483667,180,9,189,718,907,18,26,6735,856,6148.0,2350.0,8498,397055,327552.0,NaN
3177,2020-07-24T17:00:00,ITA,12,Lazio,41.89277,12.483667,184,9,193,723,916,9,18,6743,857,6155.0,2361.0,8516,399130,329353.0,NaN
3198,2020-07-25T17:00:00,ITA,12,Lazio,41.89277,12.483667,186,9,195,733,928,12,19,6749,858,6162.0,2373.0,8535,402012,331790.0,NaN
3219,2020-07-26T17:00:00,ITA,12,Lazio,41.89277,12.483667,189,9,198,737,935,7,19,6759,860,6163.0,2391.0,8554,404785,334242.0,NaN
3240,2020-07-27T17:00:00,ITA,12,Lazio,41.89277,12.483667,193,9,202,742,944,9,13,6762,861,6172.0,2395.0,8567,407440,336276.0,NaN
3261,2020-07-28T17:00:00,ITA,12,Lazio,41.89277,12.483667,194,9,203,739,942,-2,10,6773,862,6175.0,2402.0,8577,409189,337657.0,NaN
3282,2020-07-29T17:00:00,ITA,12,Lazio,41.89277,12.483667,198,9,207,762,969,27,34,6780,862,6187.0,2424.0,8611,412018,339954.0,NaN
3303,2020-07-30T17:00:00,ITA,12,Lazio,41.89277,12.483667,188,9,197,740,937,-32,18,6829,863,6193.0,2436.0,8629,414397,341764.0,NaN
3324,2020-07-31T17:00:00,ITA,12,Lazio,41.89277,12.483667,183,9,192,753,945,8,18,6839,863,6197.0,2450.0,8647,416921,343670.0,NaN

**MASK FOR ITMES NOT IN LIST**

In [ ]:
mask3 = df['denominazione_regione'].isin(['Lombardia'])
df[~mask3] #tilda character allows you suxtract the opposite.

,data,stato,codice_regione,denominazione_regione,lat,long,ricoverati_con_sintomi,terapia_intensiva,totale_ospedalizzati,isolamento_domiciliare,totale_positivi,variazione_totale_positivi,nuovi_positivi,dimessi_guariti,deceduti,casi_da_sospetto_diagnostico,casi_da_screening,totale_casi,tamponi,casi_testati,note
0,2020-02-24T18:00:00,ITA,13,Abruzzo,42.351222,13.398438,0,0,0,0,0,0,0,0,0,NaN,NaN,0,5,NaN,NaN
1,2020-02-24T18:00:00,ITA,17,Basilicata,40.639471,15.805148,0,0,0,0,0,0,0,0,0,NaN,NaN,0,0,NaN,NaN
2,2020-02-24T18:00:00,ITA,18,Calabria,38.905976,16.594402,0,0,0,0,0,0,0,0,0,NaN,NaN,0,1,NaN,NaN
3,2020-02-24T18:00:00,ITA,15,Campania,40.839566,14.250850,0,0,0,0,0,0,0,0,0,NaN,NaN,0,10,NaN,NaN
4,2020-02-24T18:00:00,ITA,8,Emilia-Romagna,44.494367,11.341721,10,2,12,6,18,0,18,0,0,NaN,NaN,18,148,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5623,2020-11-17T17:00:00,ITA,19,Sicilia,38.115697,13.362357,1505,227,1732,29024,30756,991,1698,12964,971,27716.0,16975.0,44691,835534,577818.0,NaN
5624,2020-11-17T17:00:00,ITA,9,Toscana,43.769231,11.255889,1792,277,2069,52083,54152,301,2361,28078,1967,66908.0,17289.0,84197,1363146,870134.0,effettuati 48180 tamponi rapidi antigenici di...
5625,2020-11-17T17:00:00,ITA,10,Umbria,43.106758,12.388247,368,70,438,10806,11244,5,351,7991,275,5465.0,14045.0,19510,367077,206060.0,Si fa presente come nel computo dei ricoverati...
5626,2020-11-17T17:00:00,ITA,2,Valle d'Aosta,45.737503,7.320149,152,17,169,1994,2163,-103,154,3079,257,4884.0,615.0,5499,51410,30178.0,NaN
5627,2020-11-17T17:00:00,ITA,5,Veneto,45.434905,12.338452,1980,266,2246,60825,63071,373,3124,39928,2967,27936.0,78030.0,105966,2590427,1000577.0,Tamponi antigenici 623.625 Totale popolazione ...

**SELECT ALL COLUMSN THAT ARE NUMERIC DATA TYPES**

In [ ]:
df.select_dtypes(include=[np.number])

,codice_regione,lat,long,ricoverati_con_sintomi,terapia_intensiva,totale_ospedalizzati,isolamento_domiciliare,totale_positivi,variazione_totale_positivi,nuovi_positivi,dimessi_guariti,deceduti,casi_da_sospetto_diagnostico,casi_da_screening,totale_casi,tamponi,casi_testati
0,13,42.351222,13.398438,0,0,0,0,0,0,0,0,0,NaN,NaN,0,5,NaN
1,17,40.639471,15.805148,0,0,0,0,0,0,0,0,0,NaN,NaN,0,0,NaN
2,18,38.905976,16.594402,0,0,0,0,0,0,0,0,0,NaN,NaN,0,1,NaN
3,15,40.839566,14.250850,0,0,0,0,0,0,0,0,0,NaN,NaN,0,10,NaN
4,8,44.494367,11.341721,10,2,12,6,18,0,18,0,0,NaN,NaN,18,148,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5623,19,38.115697,13.362357,1505,227,1732,29024,30756,991,1698,12964,971,27716.0,16975.0,44691,835534,577818.0
5624,9,43.769231,11.255889,1792,277,2069,52083,54152,301,2361,28078,1967,66908.0,17289.0,84197,1363146,870134.0
5625,10,43.106758,12.388247,368,70,438,10806,11244,5,351,7991,275,5465.0,14045.0,19510,367077,206060.0
5626,2,45.737503,7.320149,152,17,169,1994,2163,-103,154,3079,257,4884.0,615.0,5499,51410,30178.0
5627,5,45.434905,12.338452,1980,266,2246,60825,63071,373,3124,39928,2967,27936.0,78030.0,105966,2590427,1000577.0

**SELECT ALL COLUMSN THAT ARE CATEGORICAL DATA TYPES**

In [ ]:
df.select_dtypes(include=['O'])

,data,stato,denominazione_regione,note
0,2020-02-24T18:00:00,ITA,Abruzzo,NaN
1,2020-02-24T18:00:00,ITA,Basilicata,NaN
2,2020-02-24T18:00:00,ITA,Calabria,NaN
3,2020-02-24T18:00:00,ITA,Campania,NaN
4,2020-02-24T18:00:00,ITA,Emilia-Romagna,NaN
...,...,...,...,...
5623,2020-11-17T17:00:00,ITA,Sicilia,NaN
5624,2020-11-17T17:00:00,ITA,Toscana,effettuati 48180 tamponi rapidi antigenici di...
5625,2020-11-17T17:00:00,ITA,Umbria,Si fa presente come nel computo dei ricoverati...
5626,2020-11-17T17:00:00,ITA,Valle d'Aosta,NaN
5627,2020-11-17T17:00:00,ITA,Veneto,Tamponi antigenici 623.625 Totale popolazione ...

<h1>CLEANING DATA</h1>

In [ ]:
# Load dataset again for practice
df = pd.read_csv("https://raw.githubusercontent.com/pcm-dpc/COVID-19/master/dati-regioni/dpc-covid19-ita-regioni.csv")

**REPLACE WORD "ITA" WITH "ITALIA"**

In [ ]:
df.replace({'ITA': 'ITALIA'}, inplace=True)
df.head()

,data,stato,codice_regione,denominazione_regione,lat,long,ricoverati_con_sintomi,terapia_intensiva,totale_ospedalizzati,isolamento_domiciliare,totale_positivi,variazione_totale_positivi,nuovi_positivi,dimessi_guariti,deceduti,casi_da_sospetto_diagnostico,casi_da_screening,totale_casi,tamponi,casi_testati,note
0,2020-02-24T18:00:00,ITALIA,13,Abruzzo,42.351222,13.398438,0,0,0,0,0,0,0,0,0,NaN,NaN,0,5,NaN,NaN
1,2020-02-24T18:00:00,ITALIA,17,Basilicata,40.639471,15.805148,0,0,0,0,0,0,0,0,0,NaN,NaN,0,0,NaN,NaN
2,2020-02-24T18:00:00,ITALIA,18,Calabria,38.905976,16.594402,0,0,0,0,0,0,0,0,0,NaN,NaN,0,1,NaN,NaN
3,2020-02-24T18:00:00,ITALIA,15,Campania,40.839566,14.250850,0,0,0,0,0,0,0,0,0,NaN,NaN,0,10,NaN,NaN
4,2020-02-24T18:00:00,ITALIA,8,Emilia-Romagna,44.494367,11.341721,10,2,12,6,18,0,18,0,0,NaN,NaN,18,148,NaN,NaN

**FILL NAN values in dataset with 0**

In [ ]:
df.fillna(0, inplace=True)
df.head()

,data,stato,codice_regione,denominazione_regione,lat,long,ricoverati_con_sintomi,terapia_intensiva,totale_ospedalizzati,isolamento_domiciliare,totale_positivi,variazione_totale_positivi,nuovi_positivi,dimessi_guariti,deceduti,casi_da_sospetto_diagnostico,casi_da_screening,totale_casi,tamponi,casi_testati,note
0,2020-02-24T18:00:00,ITALIA,13,Abruzzo,42.351222,13.398438,0,0,0,0,0,0,0,0,0,0.0,0.0,0,5,0.0,0
1,2020-02-24T18:00:00,ITALIA,17,Basilicata,40.639471,15.805148,0,0,0,0,0,0,0,0,0,0.0,0.0,0,0,0.0,0
2,2020-02-24T18:00:00,ITALIA,18,Calabria,38.905976,16.594402,0,0,0,0,0,0,0,0,0,0.0,0.0,0,1,0.0,0
3,2020-02-24T18:00:00,ITALIA,15,Campania,40.839566,14.250850,0,0,0,0,0,0,0,0,0,0.0,0.0,0,10,0.0,0
4,2020-02-24T18:00:00,ITALIA,8,Emilia-Romagna,44.494367,11.341721,10,2,12,6,18,0,18,0,0,0.0,0.0,18,148,0.0,0

**Drop nulls**

In [ ]:
# Not suggested to drop straight away as Null rows may contains valuable insights for data analysis
df.dropna(inplace=True)
df.head()

,data,stato,codice_regione,denominazione_regione,lat,long,ricoverati_con_sintomi,terapia_intensiva,totale_ospedalizzati,isolamento_domiciliare,totale_positivi,variazione_totale_positivi,nuovi_positivi,dimessi_guariti,deceduti,casi_da_sospetto_diagnostico,casi_da_screening,totale_casi,tamponi,casi_testati,note
0,2020-02-24T18:00:00,ITALIA,13,Abruzzo,42.351222,13.398438,0,0,0,0,0,0,0,0,0,0.0,0.0,0,5,0.0,0
1,2020-02-24T18:00:00,ITALIA,17,Basilicata,40.639471,15.805148,0,0,0,0,0,0,0,0,0,0.0,0.0,0,0,0.0,0
2,2020-02-24T18:00:00,ITALIA,18,Calabria,38.905976,16.594402,0,0,0,0,0,0,0,0,0,0.0,0.0,0,1,0.0,0
3,2020-02-24T18:00:00,ITALIA,15,Campania,40.839566,14.250850,0,0,0,0,0,0,0,0,0,0.0,0.0,0,10,0.0,0
4,2020-02-24T18:00:00,ITALIA,8,Emilia-Romagna,44.494367,11.341721,10,2,12,6,18,0,18,0,0,0.0,0.0,18,148,0.0,0

**Let's bring back the dataset again so we can work with the two null records**

In [ ]:
df = pd.read_csv("https://raw.githubusercontent.com/pcm-dpc/COVID-19/master/dati-regioni/dpc-covid19-ita-regioni.csv")
df['casi_testati'].head(20)

0    NaN
1    NaN
2    NaN
3    NaN
4    NaN
5    NaN
6    NaN
7    NaN
8    NaN
9    NaN
10   NaN
11   NaN
12   NaN
13   NaN
14   NaN
15   NaN
16   NaN
17   NaN
18   NaN
19   NaN
Name: casi_testati, dtype: float64

**Impute null values with mean**

In [ ]:
df['casi_testati'].fillna(df['casi_testati'].mean(), inplace=True)
df['casi_testati'].head(20)

0     229381.467695
1     229381.467695
2     229381.467695
3     229381.467695
4     229381.467695
5     229381.467695
6     229381.467695
7     229381.467695
8     229381.467695
9     229381.467695
10    229381.467695
11    229381.467695
12    229381.467695
13    229381.467695
14    229381.467695
15    229381.467695
16    229381.467695
17    229381.467695
18    229381.467695
19    229381.467695
Name: casi_testati, dtype: float64

**Drop columns 'note_it' and 'note_en' **

In [ ]:
df
#df.drop(columns = ['note_it', 'note_en'], inplace = True)
#df.head() #Notice that the 'note_it' and column is gone

,data,stato,codice_regione,denominazione_regione,lat,long,ricoverati_con_sintomi,terapia_intensiva,totale_ospedalizzati,isolamento_domiciliare,totale_positivi,variazione_totale_positivi,nuovi_positivi,dimessi_guariti,deceduti,casi_da_sospetto_diagnostico,casi_da_screening,totale_casi,tamponi,casi_testati,note
0,2020-02-24T18:00:00,ITA,13,Abruzzo,42.351222,13.398438,0,0,0,0,0,0,0,0,0,NaN,NaN,0,5,2.293815e+05,NaN
1,2020-02-24T18:00:00,ITA,17,Basilicata,40.639471,15.805148,0,0,0,0,0,0,0,0,0,NaN,NaN,0,0,2.293815e+05,NaN
2,2020-02-24T18:00:00,ITA,18,Calabria,38.905976,16.594402,0,0,0,0,0,0,0,0,0,NaN,NaN,0,1,2.293815e+05,NaN
3,2020-02-24T18:00:00,ITA,15,Campania,40.839566,14.250850,0,0,0,0,0,0,0,0,0,NaN,NaN,0,10,2.293815e+05,NaN
4,2020-02-24T18:00:00,ITA,8,Emilia-Romagna,44.494367,11.341721,10,2,12,6,18,0,18,0,0,NaN,NaN,18,148,2.293815e+05,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5623,2020-11-17T17:00:00,ITA,19,Sicilia,38.115697,13.362357,1505,227,1732,29024,30756,991,1698,12964,971,27716.0,16975.0,44691,835534,5.778180e+05,NaN
5624,2020-11-17T17:00:00,ITA,9,Toscana,43.769231,11.255889,1792,277,2069,52083,54152,301,2361,28078,1967,66908.0,17289.0,84197,1363146,8.701340e+05,effettuati 48180 tamponi rapidi antigenici di...
5625,2020-11-17T17:00:00,ITA,10,Umbria,43.106758,12.388247,368,70,438,10806,11244,5,351,7991,275,5465.0,14045.0,19510,367077,2.060600e+05,Si fa presente come nel computo dei ricoverati...
5626,2020-11-17T17:00:00,ITA,2,Valle d'Aosta,45.737503,7.320149,152,17,169,1994,2163,-103,154,3079,257,4884.0,615.0,5499,51410,3.017800e+04,NaN
5627,2020-11-17T17:00:00,ITA,5,Veneto,45.434905,12.338452,1980,266,2246,60825,63071,373,3124,39928,2967,27936.0,78030.0,105966,2590427,1.000577e+06,Tamponi antigenici 623.625 Totale popolazione ...

**Drop row index 2**

In [ ]:
df.drop(2, axis=0, inplace=True)
df

,data,stato,codice_regione,denominazione_regione,lat,long,ricoverati_con_sintomi,terapia_intensiva,totale_ospedalizzati,isolamento_domiciliare,totale_positivi,variazione_totale_positivi,nuovi_positivi,dimessi_guariti,deceduti,casi_da_sospetto_diagnostico,casi_da_screening,totale_casi,tamponi,casi_testati,note
0,2020-02-24T18:00:00,ITA,13,Abruzzo,42.351222,13.398438,0,0,0,0,0,0,0,0,0,NaN,NaN,0,5,2.293815e+05,NaN
1,2020-02-24T18:00:00,ITA,17,Basilicata,40.639471,15.805148,0,0,0,0,0,0,0,0,0,NaN,NaN,0,0,2.293815e+05,NaN
3,2020-02-24T18:00:00,ITA,15,Campania,40.839566,14.250850,0,0,0,0,0,0,0,0,0,NaN,NaN,0,10,2.293815e+05,NaN
4,2020-02-24T18:00:00,ITA,8,Emilia-Romagna,44.494367,11.341721,10,2,12,6,18,0,18,0,0,NaN,NaN,18,148,2.293815e+05,NaN
5,2020-02-24T18:00:00,ITA,6,Friuli Venezia Giulia,45.649435,13.768136,0,0,0,0,0,0,0,0,0,NaN,NaN,0,58,2.293815e+05,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5623,2020-11-17T17:00:00,ITA,19,Sicilia,38.115697,13.362357,1505,227,1732,29024,30756,991,1698,12964,971,27716.0,16975.0,44691,835534,5.778180e+05,NaN
5624,2020-11-17T17:00:00,ITA,9,Toscana,43.769231,11.255889,1792,277,2069,52083,54152,301,2361,28078,1967,66908.0,17289.0,84197,1363146,8.701340e+05,effettuati 48180 tamponi rapidi antigenici di...
5625,2020-11-17T17:00:00,ITA,10,Umbria,43.106758,12.388247,368,70,438,10806,11244,5,351,7991,275,5465.0,14045.0,19510,367077,2.060600e+05,Si fa presente come nel computo dei ricoverati...
5626,2020-11-17T17:00:00,ITA,2,Valle d'Aosta,45.737503,7.320149,152,17,169,1994,2163,-103,154,3079,257,4884.0,615.0,5499,51410,3.017800e+04,NaN
5627,2020-11-17T17:00:00,ITA,5,Veneto,45.434905,12.338452,1980,266,2246,60825,63071,373,3124,39928,2967,27936.0,78030.0,105966,2590427,1.000577e+06,Tamponi antigenici 623.625 Totale popolazione ...

In [ ]:

new_column_names_dict = {
    'data': 'date',
    'stato': 'state',
    'codice_regione': 'region code',
    'denominazione_regione': 'region name',
    'lat': 'latitude',
    'long': 'longitude',
    'ricoverati_con_sintomi': 'hospitalized_with_symptoms',
    'terapia_intensiva': 'intensive care',
    'totale_ospedalizzati': 'total hospitalized',
    'isolamento_domiciliare': 'home isolation',
    'totale_positivi': 'total positives', 
    'variazione_totale_positivi': 'total positive change',
    'nuovi_positivi': 'new positives',
    'dimessi_guariti': 'discharged healed',
    'deceduti': 'deceased',
    'totale_casi': 'total cases',
    'tamponi': 'tampons',
    'casi_testati': 'total tests',
    'note_it': 'notes in italian',
    'note_en': 'notes in english'
}


df.rename(columns = new_column_names_dict, inplace = True)
df.head()

,date,state,region code,region name,latitude,longitude,hospitalized_with_symptoms,intensive care,total hospitalized,home isolation,total positives,total positive change,new positives,discharged healed,deceased,casi_da_sospetto_diagnostico,casi_da_screening,total cases,tampons,total tests,note
0,2020-02-24T18:00:00,ITA,13,Abruzzo,42.351222,13.398438,0,0,0,0,0,0,0,0,0,NaN,NaN,0,5,229381.467695,NaN
1,2020-02-24T18:00:00,ITA,17,Basilicata,40.639471,15.805148,0,0,0,0,0,0,0,0,0,NaN,NaN,0,0,229381.467695,NaN
3,2020-02-24T18:00:00,ITA,15,Campania,40.839566,14.250850,0,0,0,0,0,0,0,0,0,NaN,NaN,0,10,229381.467695,NaN
4,2020-02-24T18:00:00,ITA,8,Emilia-Romagna,44.494367,11.341721,10,2,12,6,18,0,18,0,0,NaN,NaN,18,148,229381.467695,NaN
5,2020-02-24T18:00:00,ITA,6,Friuli Venezia Giulia,45.649435,13.768136,0,0,0,0,0,0,0,0,0,NaN,NaN,0,58,229381.467695,NaN

In [ ]:
df['tampons'].apply(np.sqrt)

0          2.236068
1          0.000000
3          3.162278
4         12.165525
5          7.615773
           ...
5623     914.075489
5624    1167.538436
5625     605.868798
5626     226.737734
5627    1609.480351
Name: tampons, Length: 5627, dtype: float64

<h1>DATA AGGREGATION</h1>

**Mean of records in "age" column, grouped by column "embark_town"**

In [ ]:
df.groupby(by=['region name'])['new positives'].mean()

region name
Abruzzo                    76.858209
Basilicata                 20.078358
Calabria                   41.468165
Campania                  441.205224
Emilia-Romagna            348.436567
Friuli Venezia Giulia      74.361940
Lazio                     332.902985
Liguria                   165.772388
Lombardia                1243.843284
Marche                     89.391791
Molise                     12.194030
P.A. Bolzano               67.593284
P.A. Trento                47.156716
Piemonte                  490.847015
Puglia                    137.011194
Sardegna                   60.130597
Sicilia                   168.238806
Toscana                   314.167910
Umbria                     72.798507
Valle d'Aosta              20.518657
Veneto                    395.391791
Name: new positives, dtype: float64

**Sum of records in "new positives" column, grouped by column "region name"**

In [ ]:
df.groupby(by=['region name'])['new positives'].sum()

region name
Abruzzo                   20598
Basilicata                 5381
Calabria                  11072
Campania                 118243
Emilia-Romagna            93381
Friuli Venezia Giulia     19929
Lazio                     89218
Liguria                   44427
Lombardia                333350
Marche                    23957
Molise                     3268
P.A. Bolzano              18115
P.A. Trento               12638
Piemonte                 131547
Puglia                    36719
Sardegna                  16115
Sicilia                   45088
Toscana                   84197
Umbria                    19510
Valle d'Aosta              5499
Veneto                   105965
Name: new positives, dtype: int64

**Count of records in "new positives" column, grouped by column "region name"**

In [ ]:
df.groupby(by=['region name'])['new positives'].count()

region name
Abruzzo                  268
Basilicata               268
Calabria                 267
Campania                 268
Emilia-Romagna           268
Friuli Venezia Giulia    268
Lazio                    268
Liguria                  268
Lombardia                268
Marche                   268
Molise                   268
P.A. Bolzano             268
P.A. Trento              268
Piemonte                 268
Puglia                   268
Sardegna                 268
Sicilia                  268
Toscana                  268
Umbria                   268
Valle d'Aosta            268
Veneto                   268
Name: new positives, dtype: int64

**so we have data for 286 days from the dataset**

**Mean of "age" column, grouped by two columns: "embark_town" and "class_name"**

In [ ]:
#df.groupby(by=['date', 'region name'])['new positives'].mean()

df.groupby(by=['region name', 'date'])['new positives'].mean()

region name  date
Abruzzo      2020-02-24T18:00:00       0
             2020-02-25T18:00:00       0
             2020-02-26T18:00:00       0
             2020-02-27T18:00:00       1
             2020-02-28T18:00:00       0
                                    ...
Veneto       2020-11-13T17:00:00    3605
             2020-11-14T17:00:00    3578
             2020-11-15T17:00:00    2792
             2020-11-16T17:00:00    1966
             2020-11-17T17:00:00    3124
Name: new positives, Length: 5627, dtype: int64

<h1>COMBINING MULTIPLE DATFRAMES</h1>

In [ ]:
dfs1 = pd.read_csv("https://raw.githubusercontent.com/julia-git/Soils_DataSet/master/Soils.csv")
dfs2 = pd.read_csv("https://raw.githubusercontent.com/julia-git/Soils_DataSet/master/Soils2.csv")

**Concatenate data by column**

In [ ]:
pd.concat([dfs1, dfs2], axis=1)

,Group,Contour,Depth,Gp,Block,pH,N,Dens,P,Ca,Mg,K,Na,Conduc,Group,Contour,Depth,Gp,Block,pH,N,Dens,P,Ca,Mg,K,Na,Conduc
0,1,Top,0-10,T0,1,5.40,0.188,0.92,215,16.35,7.65,0.72,1.14,1.09,13,Top,0-10,T0,1,6.080,0.3256,0.704,257.6,19.220,8.780,0.144,0.968,0.908
1,1,Top,0-10,T0,2,NaN,0.165,1.04,208,12.25,5.15,0.71,0.94,1.35,13,Top,0-10,T0,2,6.200,0.2980,0.848,249.2,14.300,5.780,0.142,0.728,1.220
2,1,Topk,0-10,T0,3,5.14,0.260,0.95,300,13.02,5.68,0.68,0.60,1.41,13,Topk,0-10,T0,3,5.768,0.4120,0.740,359.6,15.224,6.416,0.136,0.320,1.292
3,1,Top,0-10,T0,4,5.14,0.169,1.10,248,11.92,7.88,1.09,1.01,1.64,13,Top,0-10,T0,4,5.768,0.3028,0.920,297.2,13.904,9.056,0.218,0.812,1.568
4,2,Top,10-30,T1,1,5.14,0.164,1.12,174,14.17,8.12,0.70,2.17,1.85,14,Top,10-30,T1,1,5.768,0.2968,0.944,208.4,16.604,9.344,0.140,2.204,1.820
5,2,Top,10-30,T1,2,5.10,0.094,1.22,129,8.55,6.92,0.81,2.67,3.18,14,Top,10-30,T1,2,5.720,0.2128,1.064,154.4,9.860,7.904,0.162,2.804,3.416
6,2,Top,10-30,T1,3,4.70,0.100,1.52,117,8.74,8.16,0.39,3.32,4.16,14,Top,10-30,T1,3,5.240,0.2200,1.424,140.0,10.088,9.392,0.078,3.584,4.592
7,2,Top,10-30,T1,4,4.46,0.112,1.47,170,9.49,9.16,0.70,3.76,5.14,14,Top,10-30,T1,4,4.952,0.2344,1.364,203.6,10.988,10.592,0.140,4.112,5.768
8,3,Top,30-60,T3,1,4.37,0.112,1.07,121,8.85,10.35,0.74,5.74,5.73,15,Top,30-60,T3,1,4.844,0.2344,0.884,144.8,10.220,12.020,0.148,6.488,6.476
9,3,Top,30-60,T3,2,4.39,0.058,1.54,115,4.73,6.91,0.77,5.85,6.45,15,Top,30-60,T3,2,4.868,0.1696,1.448,137.6,5.276,7.892,0.154,6.620,7.340
10,3,Top,30-60,T3,3,4.17,0.078,1.26,112,6.29,7.95,0.26,5.30,8.37,15,Top,30-60,T3,3,4.604,0.1936,1.112,134.0,7.148,9.140,0.052,5.960,9.644
11,3,Top,30-60,T3,4,3.89,0.070,1.42,117,6.61,9.76,0.41,8.30,9.21,15,Top,30-60,T3,4,4.268,0.1840,1.304,140.0,7.532,11.312,0.082,9.560,10.652
12,4,Top,60-90,T6,1,3.88,0.077,1.25,127,6.41,10.96,0.56,9.67,10.64,16,Top,60-90,T6,1,4.256,0.1924,1.100,152.0,7.292,12.752,0.112,11.204,12.368
13,4,Top,60-90,T6,2,4.07,0.046,1.54,91,3.82,6.61,0.50,7.67,10.07,16,Top,60-90,T6,2,4.484,0.1552,1.448,108.8,4.184,7.532,0.100,8.804,11.684
14,4,Top,60-90,T6,3,3.88,0.055,1.53,91,4.98,8.00,0.23,8.78,11.26,16,Top,60-90,T6,3,4.256,0.1660,1.436,108.8,5.576,9.200,0.046,10.136,13.112
15,4,Top,60-90,T6,4,3.74,0.053,1.40,79,5.86,10.14,0.41,11.04,12.15,16,Top,60-90,T6,4,4.088,0.1636,1.280,94.4,6.632,11.768,0.082,12.848,14.180
16,5,Slope,0-10,S0,1,5.11,0.247,0.94,261,13.25,7.55,0.61,1.86,2.61,17,Slope,0-10,S0,1,5.732,0.3964,0.728,312.8,15.500,8.660,0.122,1.832,2.732
17,5,Slope,0-10,S0,2,5.46,0.298,0.96,300,12.30,7.50,0.68,2.00,1.98,17,Slope,0-10,S0,2,6.152,0.4576,0.752,359.6,14.360,8.600,0.136,2.000,1.976
18,5,Slope,0-10,S0,3,NaN,0.145,1.10,242,9.66,6.76,0.63,1.01,0.76,17,Slope,0-10,S0,3,6.332,0.2740,0.920,290.0,11.192,7.712,0.126,0.812,0.512
19,5,Slope,0-10,S0,4,5.85,0.186,1.20,229,13.78,7.12,0.62,3.09,2.85,17,Slope,0-10,S0,4,6.620,0.3232,1.040,274.4,16.136,8.144,0.124,3.308,3.020
20,6,Slope,10-30,S1,1,4.57,0.102,1.37,156,8.58,9.92,0.63,3.67,3.24,18,Slope,10-30,S1,1,5.084,0.2224,1.244,186.8,9.896,11.504,0.126,4.004,3.488
21,6,Slope,10-30,S1,2,5.11,0.097,1.30,139,8.58,8.69,0.42,4.70,4.63,18,Slope,10-30,S1,2,5.732,0.2164,1.160,166.4,9.896,10.028,0.084,5.240,5.156
22,6,Slope,10-30,S1,3,4.78,0.122,1.30,214,8.22,7.75,0.32,3.07,3.67,18,Slope,10-30,S1,3,5.336,0.2464,1.160,256.4,9.464,8.900,0.064,3.284,4.004
23,6,Slope,10-30,S1,4,6.67,0.083,1.42,132,12.68,9.56,0.55,8.30,8.10,18,Slope,10-30,S1,4,7.604,0.1996,1.304,158.0,14.816,11.072,0.110,9.560,9.320
24,7,Slope,30-60,S3,1,3.96,0.059,1.53,98,4.80,10.00,0.36,6.52,7.72,19,Slope,30-60,S3,1,4.352,0.1708,1.436,117.2,5.360,11.600,0.072,7.424,8.864
25,7,Slope,30-60,S3,2,4.00,0.050,1.50,115,5.06,8.91,0.28,7.91,9.78,19,Slope,30-60,S3,2,4.400,0.1600,1.400,137.6,5.672,10.292,0.056,9.092,11.336
26,7,Slope,30-60,S3,3,4.12,0.086,1.55,148,6.16,7.58,0.16,6.39,9.07,19,Slope,30-60,S3,3,4.544,0.2032,1.460,177.2,6.992,8.696,0.032,7.268,10.484
27,7,Slope,30-60,S3,4,4.99,0.048,1.46,97,7.49,9.38,0.40,9.70,9.13,19,Slope,30-60,S3,4,5.588,0.1576,1.352,116.0,8.588,10.856,0.080,11.240,10.556
28,8,Slope,60-90,S6,1,3.80,0.049,1.48,108,3.82,8.80,0.24,9.57,11.57,20,Slope,60-90,S6,1,4.160,0.1588,1.376,129.2,4.184,10.160,0.048,11.084,13.484
29,8,Slope,60-90,S6,2,3.96,0.036,1.28,103,4.78,7.29,0.24,9.67,11.42,20,Slope,60-90,S6,2,4.352,0.1432,1.136,123.2,5.336,8.348,0.048,11.204,13.304
30,8,Slope,60-90,S6,3,3.93,0.048,1.42,109,4.93,7.47,0.14,9.65,13.32,20,Slope,60-90,S6,3,4.316,0.1576,1.304,130.4,5.516,8.564,0.028,11.180,15.584
31,8,Slope,60-90,S6,4,4.02,0.039,1.51,100,5.66,8.84,0.37,10.54,11.57,20,Slope,60-90,S6,4,4.424,0.1468,1.412,119.6,6.392,10.208,0.074,12.248,13.484
32,9,Depression,0-10,D0,1,5.24,0.194,1.00,445,12.27,6.27,0.72,1.02,0.75,21,Depression,0-10,D0,1,5.888,0.3328,0.800,533.6,14.324,7.124,0.144,0.824,0.500
33,9,Depression,0-10,D0,2,5.20,0.256,0.78,380,11.39,7.55,0.78,1.63,2.20,21,Depression,0-10,D0,2,5.840,0.4072,0.536,455.6,13.268,8.660,0.156,1.556,2.240
34,9,Depression,0-10,D0,3,5.30,0.136,1.00,259,9.96,8.08,0.45,1.97,2.27,21,Depression,0-10,D0,3,5.960,0.2632,0.800,310.4,11.552,9.296,0.090,1.964,2.324
35,9,Depression,0-10,D0,4,5.67,0.127,1.13,248,9.12,7.04,0.55,1.43,0.67,21,Depression,0-10,D0,4,6.404,0.2524,0.956,297.2,10.544,8.048,0.110,1.316,0.404
36,10,Depression,10-30,D1,1,4.46,0.087,1.24,276,7.24,9.40,0.43,4.17,5.08,22,Depression,10-30,D1,1,4.952,0.2044,1.088,330.8,8.288,10.880,0.086,4.604,5.696
37,10,Depression,10-30,D1,2,4.91,0.092,1.47,158,7.37,10.57,0.59,5.07,6.37,22,Depression,10-30,D1,2,5.492,0.2104,1.364,189.2,8.444,12.284,0.118,5.684,7.244
38,10,Depression,10-30,D1,3,4.79,0.047,1.46,121,6.99,9.91,0.30,5.15,6.82,22,Depression,10-30,D1,3,5.348,0.1564,1.352,144.8,7.988,11.492,0.060,5.780,7.784
39,10,Depression,10-30,D1,4,5.36,0.095,1.26,195,8.59,8.66,0.48,4.17,3.65,22,Depression,10-30,D1,4,6.032,0.2140,1.112,233.6,9.908,9.992,0.096,4.604,3.980
40,11,Depression,30-60,D3,1,3.94,0.054,1.60,148,4.85,9.62,0.18,7.20,10.14,23,Depression,30-60,D3,1,4.328,0.1648,1.520,177.2,5.420,11.144,0.036,8.240,11.768
41,11,Depression,30-60,D3,2,4.52,0.051,1.53,115,6.34,9.78,0.34,8.52,9.74,23,Depression,30-60,D3,2,5.024,0.1612,1.436,137.6,7.208,11.336,0.068,9.824,11.288
42,11,Depression,30-60,D3,3,4.35,0.032,1.55,82,5.99,9.73,0.22,7.02,8.60,23,Depression,30-60,D3,3,4.820,0.1384,1.460,98.0,6.788,11.276,0.044,8.024,9.920
43,11,Depression,30-60,D3,4,4.64,0.065,1.46,152,4.43,10.54,0.22,7.61,9.09,23,Depression,30-60,D3,4,5.168,0.1780,1.352,182.0,4.916,12.248,0.044,8.732,10.508
44,12,Depression,60-90,D6,1,3.82,0.038,1.40,105,4.65,9.85,0.18,10.15,12.26,24,Depression,60-90,D6,1,4.184,0.1456,1.280,125.6,5.180,11.420,0.036,11.780,14.312
45,12,Depression,60-90,D6,2,4.24,0.035,1.47,100,4.56,8.95,0.33,10.51,11.29,24,Depression,60-90,D6,2,4.688,0.1420,1.364,119.6,5.072,10.340,0.066,12.212,13.148
46,12,Depression,60-90,D6,3,4.22,0.030,1.56,97,5.29,8.37,0.14,8.27,9.51,24,Depression,60-90,D6,3,4.664,0.1360,1.472,116.0,5.948,9.644,0.028,9.524,11.012
47,12,Depression,60-90,D6,4,4.41,0.058,1.58,130,4.58,9.46,0.14,9.28,12.69,24,Depression,60-90,D6,4,4.892,0.1696,1.496,155.6,5.096,10.952,0.028,10.736,14.828

**Concatenate data by row**

In [ ]:
pd.concat([dfs1, dfs2], axis=0)

,Group,Contour,Depth,Gp,Block,pH,N,Dens,P,Ca,Mg,K,Na,Conduc
0,1,Top,0-10,T0,1,5.400,0.1880,0.920,215.0,16.350,7.650,0.720,1.140,1.090
1,1,Top,0-10,T0,2,NaN,0.1650,1.040,208.0,12.250,5.150,0.710,0.940,1.350
2,1,Topk,0-10,T0,3,5.140,0.2600,0.950,300.0,13.020,5.680,0.680,0.600,1.410
3,1,Top,0-10,T0,4,5.140,0.1690,1.100,248.0,11.920,7.880,1.090,1.010,1.640
4,2,Top,10-30,T1,1,5.140,0.1640,1.120,174.0,14.170,8.120,0.700,2.170,1.850
5,2,Top,10-30,T1,2,5.100,0.0940,1.220,129.0,8.550,6.920,0.810,2.670,3.180
6,2,Top,10-30,T1,3,4.700,0.1000,1.520,117.0,8.740,8.160,0.390,3.320,4.160
7,2,Top,10-30,T1,4,4.460,0.1120,1.470,170.0,9.490,9.160,0.700,3.760,5.140
8,3,Top,30-60,T3,1,4.370,0.1120,1.070,121.0,8.850,10.350,0.740,5.740,5.730
9,3,Top,30-60,T3,2,4.390,0.0580,1.540,115.0,4.730,6.910,0.770,5.850,6.450
10,3,Top,30-60,T3,3,4.170,0.0780,1.260,112.0,6.290,7.950,0.260,5.300,8.370
11,3,Top,30-60,T3,4,3.890,0.0700,1.420,117.0,6.610,9.760,0.410,8.300,9.210
12,4,Top,60-90,T6,1,3.880,0.0770,1.250,127.0,6.410,10.960,0.560,9.670,10.640
13,4,Top,60-90,T6,2,4.070,0.0460,1.540,91.0,3.820,6.610,0.500,7.670,10.070
14,4,Top,60-90,T6,3,3.880,0.0550,1.530,91.0,4.980,8.000,0.230,8.780,11.260
15,4,Top,60-90,T6,4,3.740,0.0530,1.400,79.0,5.860,10.140,0.410,11.040,12.150
16,5,Slope,0-10,S0,1,5.110,0.2470,0.940,261.0,13.250,7.550,0.610,1.860,2.610
17,5,Slope,0-10,S0,2,5.460,0.2980,0.960,300.0,12.300,7.500,0.680,2.000,1.980
18,5,Slope,0-10,S0,3,NaN,0.1450,1.100,242.0,9.660,6.760,0.630,1.010,0.760
19,5,Slope,0-10,S0,4,5.850,0.1860,1.200,229.0,13.780,7.120,0.620,3.090,2.850
20,6,Slope,10-30,S1,1,4.570,0.1020,1.370,156.0,8.580,9.920,0.630,3.670,3.240
21,6,Slope,10-30,S1,2,5.110,0.0970,1.300,139.0,8.580,8.690,0.420,4.700,4.630
22,6,Slope,10-30,S1,3,4.780,0.1220,1.300,214.0,8.220,7.750,0.320,3.070,3.670
23,6,Slope,10-30,S1,4,6.670,0.0830,1.420,132.0,12.680,9.560,0.550,8.300,8.100
24,7,Slope,30-60,S3,1,3.960,0.0590,1.530,98.0,4.800,10.000,0.360,6.520,7.720
25,7,Slope,30-60,S3,2,4.000,0.0500,1.500,115.0,5.060,8.910,0.280,7.910,9.780
26,7,Slope,30-60,S3,3,4.120,0.0860,1.550,148.0,6.160,7.580,0.160,6.390,9.070
27,7,Slope,30-60,S3,4,4.990,0.0480,1.460,97.0,7.490,9.380,0.400,9.700,9.130
28,8,Slope,60-90,S6,1,3.800,0.0490,1.480,108.0,3.820,8.800,0.240,9.570,11.570
29,8,Slope,60-90,S6,2,3.960,0.0360,1.280,103.0,4.780,7.290,0.240,9.670,11.420
30,8,Slope,60-90,S6,3,3.930,0.0480,1.420,109.0,4.930,7.470,0.140,9.650,13.320
31,8,Slope,60-90,S6,4,4.020,0.0390,1.510,100.0,5.660,8.840,0.370,10.540,11.570
32,9,Depression,0-10,D0,1,5.240,0.1940,1.000,445.0,12.270,6.270,0.720,1.020,0.750
33,9,Depression,0-10,D0,2,5.200,0.2560,0.780,380.0,11.390,7.550,0.780,1.630,2.200
34,9,Depression,0-10,D0,3,5.300,0.1360,1.000,259.0,9.960,8.080,0.450,1.970,2.270
35,9,Depression,0-10,D0,4,5.670,0.1270,1.130,248.0,9.120,7.040,0.550,1.430,0.670
36,10,Depression,10-30,D1,1,4.460,0.0870,1.240,276.0,7.240,9.400,0.430,4.170,5.080
37,10,Depression,10-30,D1,2,4.910,0.0920,1.470,158.0,7.370,10.570,0.590,5.070,6.370
38,10,Depression,10-30,D1,3,4.790,0.0470,1.460,121.0,6.990,9.910,0.300,5.150,6.820
39,10,Depression,10-30,D1,4,5.360,0.0950,1.260,195.0,8.590,8.660,0.480,4.170,3.650
40,11,Depression,30-60,D3,1,3.940,0.0540,1.600,148.0,4.850,9.620,0.180,7.200,10.140
41,11,Depression,30-60,D3,2,4.520,0.0510,1.530,115.0,6.340,9.780,0.340,8.520,9.740
42,11,Depression,30-60,D3,3,4.350,0.0320,1.550,82.0,5.990,9.730,0.220,7.020,8.600
43,11,Depression,30-60,D3,4,4.640,0.0650,1.460,152.0,4.430,10.540,0.220,7.610,9.090
44,12,Depression,60-90,D6,1,3.820,0.0380,1.400,105.0,4.650,9.850,0.180,10.150,12.260
45,12,Depression,60-90,D6,2,4.240,0.0350,1.470,100.0,4.560,8.950,0.330,10.510,11.290
46,12,Depression,60-90,D6,3,4.220,0.0300,1.560,97.0,5.290,8.370,0.140,8.270,9.510
47,12,Depression,60-90,D6,4,4.410,0.0580,1.580,130.0,4.580,9.460,0.140,9.280,12.690
0,13,Top,0-10,T0,1,6.080,0.3256,0.704,257.6,19.220,8.780,0.144,0.968,0.908
1,13,Top,0-10,T0,2,6.200,0.2980,0.848,249.2,14.300,5.780,0.142,0.728,1.220
2,13,Topk,0-10,T0,3,5.768,0.4120,0.740,359.6,15.224,6.416,0.136,0.320,1.292
3,13,Top,0-10,T0,4,5.768,0.3028,0.920,297.2,13.904,9.056,0.218,0.812,1.568
4,14,Top,10-30,T1,1,5.768,0.2968,0.944,208.4,16.604,9.344,0.140,2.204,1.820
5,14,Top,10-30,T1,2,5.720,0.2128,1.064,154.4,9.860,7.904,0.162,2.804,3.416
6,14,Top,10-30,T1,3,5.240,0.2200,1.424,140.0,10.088,9.392,0.078,3.584,4.592
7,14,Top,10-30,T1,4,4.952,0.2344,1.364,203.6,10.988,10.592,0.140,4.112,5.768
8,15,Top,30-60,T3,1,4.844,0.2344,0.884,144.8,10.220,12.020,0.148,6.488,6.476
9,15,Top,30-60,T3,2,4.868,0.1696,1.448,137.6,5.276,7.892,0.154,6.620,7.340
10,15,Top,30-60,T3,3,4.604,0.1936,1.112,134.0,7.148,9.140,0.052,5.960,9.644
11,15,Top,30-60,T3,4,4.268,0.1840,1.304,140.0,7.532,11.312,0.082,9.560,10.652
12,16,Top,60-90,T6,1,4.256,0.1924,1.100,152.0,7.292,12.752,0.112,11.204,12.368
13,16,Top,60-90,T6,2,4.484,0.1552,1.448,108.8,4.184,7.532,0.100,8.804,11.684
14,16,Top,60-90,T6,3,4.256,0.1660,1.436,108.8,5.576,9.200,0.046,10.136,13.112
15,16,Top,60-90,T6,4,4.088,0.1636,1.280,94.4,6.632,11.768,0.082,12.848,14.180
16,17,Slope,0-10,S0,1,5.732,0.3964,0.728,312.8,15.500,8.660,0.122,1.832,2.732
17,17,Slope,0-10,S0,2,6.152,0.4576,0.752,359.6,14.360,8.600,0.136,2.000,1.976
18,17,Slope,0-10,S0,3,6.332,0.2740,0.920,290.0,11.192,7.712,0.126,0.812,0.512
19,17,Slope,0-10,S0,4,6.620,0.3232,1.040,274.4,16.136,8.144,0.124,3.308,3.020
20,18,Slope,10-30,S1,1,5.084,0.2224,1.244,186.8,9.896,11.504,0.126,4.004,3.488
21,18,Slope,10-30,S1,2,5.732,0.2164,1.160,166.4,9.896,10.028,0.084,5.240,5.156
22,18,Slope,10-30,S1,3,5.336,0.2464,1.160,256.4,9.464,8.900,0.064,3.284,4.004
23,18,Slope,10-30,S1,4,7.604,0.1996,1.304,158.0,14.816,11.072,0.110,9.560,9.320
24,19,Slope,30-60,S3,1,4.352,0.1708,1.436,117.2,5.360,11.600,0.072,7.424,8.864
25,19,Slope,30-60,S3,2,4.400,0.1600,1.400,137.6,5.672,10.292,0.056,9.092,11.336
26,19,Slope,30-60,S3,3,4.544,0.2032,1.460,177.2,6.992,8.696,0.032,7.268,10.484
27,19,Slope,30-60,S3,4,5.588,0.1576,1.352,116.0,8.588,10.856,0.080,11.240,10.556
28,20,Slope,60-90,S6,1,4.160,0.1588,1.376,129.2,4.184,10.160,0.048,11.084,13.484
29,20,Slope,60-90,S6,2,4.352,0.1432,1.136,123.2,5.336,8.348,0.048,11.204,13.304
30,20,Slope,60-90,S6,3,4.316,0.1576,1.304,130.4,5.516,8.564,0.028,11.180,15.584
31,20,Slope,60-90,S6,4,4.424,0.1468,1.412,119.6,6.392,10.208,0.074,12.248,13.484
32,21,Depression,0-10,D0,1,5.888,0.3328,0.800,533.6,14.324,7.124,0.144,0.824,0.500
33,21,Depression,0-10,D0,2,5.840,0.4072,0.536,455.6,13.268,8.660,0.156,1.556,2.240
34,21,Depression,0-10,D0,3,5.960,0.2632,0.800,310.4,11.552,9.296,0.090,1.964,2.324
35,21,Depression,0-10,D0,4,6.404,0.2524,0.956,297.2,10.544,8.048,0.110,1.316,0.404
36,22,Depression,10-30,D1,1,4.952,0.2044,1.088,330.8,8.288,10.880,0.086,4.604,5.696
37,22,Depression,10-30,D1,2,5.492,0.2104,1.364,189.2,8.444,12.284,0.118,5.684,7.244
38,22,Depression,10-30,D1,3,5.348,0.1564,1.352,144.8,7.988,11.492,0.060,5.780,7.784
39,22,Depression,10-30,D1,4,6.032,0.2140,1.112,233.6,9.908,9.992,0.096,4.604,3.980
40,23,Depression,30-60,D3,1,4.328,0.1648,1.520,177.2,5.420,11.144,0.036,8.240,11.768
41,23,Depression,30-60,D3,2,5.024,0.1612,1.436,137.6,7.208,11.336,0.068,9.824,11.288
42,23,Depression,30-60,D3,3,4.820,0.1384,1.460,98.0,6.788,11.276,0.044,8.024,9.920
43,23,Depression,30-60,D3,4,5.168,0.1780,1.352,182.0,4.916,12.248,0.044,8.732,10.508
44,24,Depression,60-90,D6,1,4.184,0.1456,1.280,125.6,5.180,11.420,0.036,11.780,14.312
45,24,Depression,60-90,D6,2,4.688,0.1420,1.364,119.6,5.072,10.340,0.066,12.212,13.148
46,24,Depression,60-90,D6,3,4.664,0.1360,1.472,116.0,5.948,9.644,0.028,9.524,11.012
47,24,Depression,60-90,D6,4,4.892,0.1696,1.496,155.6,5.096,10.952,0.028,10.736,14.828

**Outer join on the two dataframes on the "Contour" columns**

In [ ]:
pd.merge(dfs1, dfs2, left_on='Contour', right_on='Contour', how='outer')

,Group_x,Contour,Depth_x,Gp_x,Block_x,pH_x,N_x,Dens_x,P_x,Ca_x,Mg_x,K_x,Na_x,Conduc_x,Group_y,Depth_y,Gp_y,Block_y,pH_y,N_y,Dens_y,P_y,Ca_y,Mg_y,K_y,Na_y,Conduc_y
0,1,Top,0-10,T0,1,5.40,0.188,0.92,215,16.35,7.65,0.72,1.14,1.09,13,0-10,T0,1,6.080,0.3256,0.704,257.6,19.220,8.780,0.144,0.968,0.908
1,1,Top,0-10,T0,1,5.40,0.188,0.92,215,16.35,7.65,0.72,1.14,1.09,13,0-10,T0,2,6.200,0.2980,0.848,249.2,14.300,5.780,0.142,0.728,1.220
2,1,Top,0-10,T0,1,5.40,0.188,0.92,215,16.35,7.65,0.72,1.14,1.09,13,0-10,T0,4,5.768,0.3028,0.920,297.2,13.904,9.056,0.218,0.812,1.568
3,1,Top,0-10,T0,1,5.40,0.188,0.92,215,16.35,7.65,0.72,1.14,1.09,14,10-30,T1,1,5.768,0.2968,0.944,208.4,16.604,9.344,0.140,2.204,1.820
4,1,Top,0-10,T0,1,5.40,0.188,0.92,215,16.35,7.65,0.72,1.14,1.09,14,10-30,T1,2,5.720,0.2128,1.064,154.4,9.860,7.904,0.162,2.804,3.416
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
733,12,Depression,60-90,D6,4,4.41,0.058,1.58,130,4.58,9.46,0.14,9.28,12.69,23,30-60,D3,4,5.168,0.1780,1.352,182.0,4.916,12.248,0.044,8.732,10.508
734,12,Depression,60-90,D6,4,4.41,0.058,1.58,130,4.58,9.46,0.14,9.28,12.69,24,60-90,D6,1,4.184,0.1456,1.280,125.6,5.180,11.420,0.036,11.780,14.312
735,12,Depression,60-90,D6,4,4.41,0.058,1.58,130,4.58,9.46,0.14,9.28,12.69,24,60-90,D6,2,4.688,0.1420,1.364,119.6,5.072,10.340,0.066,12.212,13.148
736,12,Depression,60-90,D6,4,4.41,0.058,1.58,130,4.58,9.46,0.14,9.28,12.69,24,60-90,D6,3,4.664,0.1360,1.472,116.0,5.948,9.644,0.028,9.524,11.012
737,12,Depression,60-90,D6,4,4.41,0.058,1.58,130,4.58,9.46,0.14,9.28,12.69,24,60-90,D6,4,4.892,0.1696,1.496,155.6,5.096,10.952,0.028,10.736,14.828

<h1>EXPORTING DATA</h1>

In [ ]:
#Export data to csv, delimit by tab
dfs1.to_csv('myDataFrame.csv', sep='\t')

In [ ]:
#Export data to excel
writer = pd.ExcelWriter('myDataFrame.xlsx') 
dfs1.to_excel(writer, 'DataFrame') 
writer.save()

In [ ]:
# Other notes
import pandas as pd
import numpy as np


# Reading in CSV files. Use the read_csv command.
# More options: https://pandas.pydata.org/pandas-docs/stable/io.html
df = pd.read_csv('salaries.csv')

print(df)


# You can select columns with a bracket call:
print(df['Name'])


print(df['Salary'])


# Select multiple columns with a list of column names.
# Since you are passing in a list, you see two sets of []
print(df[['Name','Salary']])


# Similar to NumPy, you can create calls of min(), max(), mean(), etc...
# on a pandas dataframe.

print(df['Age'].mean())


# Just like Numpy, we can use conditional filtering to select rows that meet
# certain critera. Like choosing rows where the Age value is greater than 30

ser_of_bool = df['Age'] > 30
print(ser_of_bool)

# Use this filter of booleans to then select the rows

age_filter = df['Age'] > 30

# Pass it to the dataframe
print(df[age_filter])


# More commonly done all in one step:
df[df['Age'] > 30]


# There are lots of other commands you can do with pandas!
# But for now, we'll just talk about a few more, and then introduce the rest
# as we continue through the course :)

df['Age'].unique() # list of unique values for Age
df['Age'].nunique() # number of unqiue values
df.info() # General info about your dataframe
df.describe() # Statistics about your dataframe
df.columns # Grab a list of all columns
df.index # Create an index list
# You can convert a numpy matrix to a dataframe with:
mat = np.arange(50).reshape(5,10)

df = pd.DataFrame(data=mat)


mat = np.arange(0,10).reshape(5,2)

df = pd.DataFrame(data=mat, columns=['A', 'B'])

print(df)

In [ ]:
# Exercises
#######
# TASK 1: Import pandas and numpy
######
import numpy as np
import pandas as pd


#######
# TASK 2: Set Numpy's random number generator seed to 101
######

np.random.seed(101)

#######
# TASK 3: Create a NumPy Matrix of 100 rows by 5 columns consisting of
#         random integers from 1-100. (Keep in mind that the upper
#         limit may be exclusive.)
######
mat = np.random.randint(1,101,(100,5))
print(mat)


#######
# TASK 4: Now use pd.DataFrame() to read in this numpy array as a dataframe.
#         Simple pass in the numpy array into that function to get back a
#         dataframe. Pandas will auto label the columns to 0-4
######

df = pd.DataFrame(mat)
print(df)

#######
# TASK 5: Using your previously created DataFrame, use [df.columns = [...]]
#         (https://stackoverflow.com/questions/11346283/renaming-columns-in-pandas)
#         to rename the pandas columns to be ['f1','f2','f3','f4','label'].
######

df.columns = ['f1','f2','f3','f4','label']

#######
# TASK 6: Alright, all the other tasks were hopefully straightforward.
#         This final task will allow you to quickly check to see if you are at
#         the right level with pandas! Do the following:
#         Create a dataframe with the columns ['A','B','C','D'] with each column
#         having 50 rows of random numbers for data. The random numbers should be
#         between 0 and 100. (Hint: Use numpy to create the numbers, then pass
#         it in to pd.DataFrame(), check out the data= and index= parameters
#         for that call.)
random_numbers = np.random.randint(0,100,200)
random_mat = random_numbers.reshape(50,4)
col_names = 'A B C D'.split()
df = pd.DataFrame(data = random_mat,columns=col_names)